raylib-cpp: raylib::AudioDevice Class Reference
raylib::AudioDevice Class Reference
Audio device management functions.
#include <AudioDevice.hpp>
Public Member Functions
AudioDevice (bool lateInit=false)
Initialize audio device and context.
~AudioDevice ()
Close the audio device and context.
AudioDevice & SetVolume (float volume)
Set master volume (listener).
Static Public Member Functions
static void Close ()
Close the audio device and context.
static void Init ()
Initialize audio device and context.
static bool IsReady ()
Check if audio device has been initialized successfully.
Detailed Description
Audio device management functions.
Definition at line 12 of file AudioDevice.hpp.
Constructor & Destructor Documentation
AudioDevice()
raylib::AudioDevice::AudioDevice (bool lateInit = false) inline explicit
Initialize audio device and context.
Parameters
lateInit Whether or not to post-pone initializing the context.
Exceptions
raylib::RaylibException Throws if the AudioDevice failed to initialize.
Definition at line 21 of file AudioDevice.hpp.
References Init().
~AudioDevice()
raylib::AudioDevice::~AudioDevice () inline
Close the audio device and context.
Definition at line 30 of file AudioDevice.hpp.
References Close().
Member Function Documentation
Close()
static void raylib::AudioDevice::Close () inline static
Close the audio device and context.
Definition at line 47 of file AudioDevice.hpp.
Referenced by ~AudioDevice().
Init()
static void raylib::AudioDevice::Init () inline static
Initialize audio device and context.
Exceptions
raylib::RaylibException Throws if the AudioDevice failed to initialize.
Definition at line 37 of file AudioDevice.hpp.
References IsReady().
Referenced by AudioDevice().
IsReady()
static bool raylib::AudioDevice::IsReady () inline static
Check if audio device has been initialized successfully.
Definition at line 52 of file AudioDevice.hpp.
Referenced by Init().
SetVolume()
AudioDevice & raylib::AudioDevice::SetVolume (float volume) inline
Set master volume (listener).
Parameters
volume The desired volume to set.
Definition at line 59 of file AudioDevice.hpp.