raylib-cpp: raylib::AutomationEventList Class Reference
raylib::AutomationEventList Class Reference
AutomationEventList management functions.
#include <AutomationEventList.hpp>
Public Member Functions
AutomationEventList ()
Load an empty automation events list.
AutomationEventList (AutomationEventList &&other) noexcept
AutomationEventList (const ::AutomationEventList &automationEventList)
AutomationEventList (const AutomationEventList &)=delete
AutomationEventList (const char *fileName)
Load automation events list from file.
bool Export (const char *fileName)
unsigned int GetCapacity () const
Retrieves the capacity value for the object.
unsigned int GetCount () const
Retrieves the count value for the object.
AutomationEvent * GetEvents () const
Retrieves the events value for the object.
bool IsValid ()
void Load (const char *fileName)
Load audio stream (to stream raw audio pcm data)
AutomationEventList & operator= (AutomationEventList &&other) noexcept
AutomationEventList & operator= (const ::AutomationEventList &other)
AutomationEventList & operator= (const AutomationEventList &)=delete
void Play (int index)
void Set ()
void SetBaseFrame (int frame)
void StartRecording ()
void StopRecording ()
void Unload ()
Update audio stream buffers with data.
Protected Member Functions
void set (const ::AutomationEventList &other)
Detailed Description
AutomationEventList management functions.
Definition at line 12 of file AutomationEventList.hpp.
Constructor & Destructor Documentation
AutomationEventList() [1/4]
raylib::AutomationEventList::AutomationEventList (const ::AutomationEventList & automationEventList) inline
Definition at line 14 of file AutomationEventList.hpp.
AutomationEventList() [2/4]
raylib::AutomationEventList::AutomationEventList () inline
Load an empty automation events list.
Definition at line 22 of file AutomationEventList.hpp.
AutomationEventList() [3/4]
raylib::AutomationEventList::AutomationEventList (const char * fileName) inline
Load automation events list from file.
Parameters
fileName The file path to load the automation events list from.
Definition at line 29 of file AutomationEventList.hpp.
References Load().
AutomationEventList() [4/4]
raylib::AutomationEventList::AutomationEventList (AutomationEventList && other) inline noexcept
Definition at line 33 of file AutomationEventList.hpp.
~AutomationEventList()
raylib::AutomationEventList::~AutomationEventList () inline
Definition at line 41 of file AutomationEventList.hpp.
Member Function Documentation
Export()
bool raylib::AutomationEventList::Export (const char * fileName) inline
Definition at line 104 of file AutomationEventList.hpp.
GetCapacity()
unsigned int raylib::AutomationEventList::GetCapacity () const inline
Retrieves the capacity value for the object.
Returns
The capacity value of the object.
Definition at line 43 of file AutomationEventList.hpp.
GetCount()
unsigned int raylib::AutomationEventList::GetCount () const inline
Retrieves the count value for the object.
Returns
The count value of the object.
Definition at line 44 of file AutomationEventList.hpp.
GetEvents()
AutomationEvent * raylib::AutomationEventList::GetEvents () const inline
Retrieves the events value for the object.
Returns
The events value of the object.
Definition at line 45 of file AutomationEventList.hpp.
IsValid()
bool raylib::AutomationEventList::IsValid () inline
Definition at line 102 of file AutomationEventList.hpp.
Load()
void raylib::AutomationEventList::Load (const char * fileName) inline
Load audio stream (to stream raw audio pcm data)
Exceptions
raylib::RaylibException Throws if the AutomationEventList failed to load.
Definition at line 74 of file AutomationEventList.hpp.
References Unload().
Referenced by AutomationEventList().
operator=() [1/2]
AutomationEventList & raylib::AutomationEventList::operator= (AutomationEventList && other) inline noexcept
Definition at line 54 of file AutomationEventList.hpp.
operator=() [2/2]
AutomationEventList & raylib::AutomationEventList::operator= (const ::AutomationEventList & other) inline
Definition at line 47 of file AutomationEventList.hpp.
Play()
void raylib::AutomationEventList::Play (int index) inline
Definition at line 123 of file AutomationEventList.hpp.
Set()
void raylib::AutomationEventList::Set () inline
Definition at line 106 of file AutomationEventList.hpp.
set()
void raylib::AutomationEventList::set (const ::AutomationEventList & other) inline protected
Definition at line 132 of file AutomationEventList.hpp.
SetBaseFrame()
void raylib::AutomationEventList::SetBaseFrame (int frame) inline
Definition at line 108 of file AutomationEventList.hpp.
StartRecording()
void raylib::AutomationEventList::StartRecording () inline
Definition at line 113 of file AutomationEventList.hpp.
StopRecording()
void raylib::AutomationEventList::StopRecording () inline
Definition at line 118 of file AutomationEventList.hpp.
Unload()
void raylib::AutomationEventList::Unload () inline
Update audio stream buffers with data.
Definition at line 85 of file AutomationEventList.hpp.
Referenced by Load().