raylib-cpp: raylib::Image Class Reference
raylib::Image Class Reference
Image type, bpp always RGBA (32bit)
#include <Image.hpp>
Public Member Functions
Image (const ::Font &font, const std::string &text, float fontSize, float spacing, ::Color tint={255, 255, 255, 255})
Image (const ::Image &image)
Image (const ::Texture2D &texture)
Load an image from the given file.
Image (const Image &other)
Image (const std::string &fileName)
Load an image from the given file.
Image (const std::string &fileName, int *frames)
Load an animation image from the given file.
Image (const std::string &fileName, int width, int height, int format, int headerSize=0)
Load a raw image from the given file, with the provided width, height, and formats.
Image (const std::string &fileType, const unsigned char *fileData, int dataSize)
Load an image from the given file.
Image (const std::string &text, int fontSize, ::Color color={255, 255, 255, 255})
Image (Image &&other) noexcept
Image (int width, int height, ::Color color={255, 255, 255, 255})
Image (void *data=nullptr, int width=0, int height=0, int mipmaps=1, int format=PIXELFORMAT_UNCOMPRESSED_R8G8B8A8)
Image & AlphaClear (::Color color, float threshold)
Clear alpha channel to desired color.
Image & AlphaCrop (float threshold)
Crop image depending on alpha value.
Image & AlphaMask (const ::Image &alphaMask)
Apply alpha mask to image.
Image & AlphaPremultiply ()
Premultiply alpha channel.
::Image Channel (int selectedChannel)
Create an image from a selected channel of another image (GRAYSCALE)
Image & ClearBackground (::Color color={0, 0, 0, 255})
Clear image background with given color.
Image & ColorBrightness (int brightness)
Modify image color: brightness.
Image & ColorContrast (float contrast)
Modify image color: contrast.
Image & ColorGrayscale ()
Modify image color: grayscale.
Image & ColorInvert ()
Modify image color: invert.
Image & ColorReplace (::Color color, ::Color replace)
Modify image color: replace color.
Image & ColorTint (::Color color={255, 255, 255, 255})
Modify image color: tint.
::Image Copy () const
Create an image duplicate (useful for transformations)
Image & Crop (::Rectangle crop)
Crop an image to area defined by a rectangle.
Image & Crop (::Vector2 size)
Crop an image to a new given width and height based on a vector.
Image & Crop (int newWidth, int newHeight)
Crop an image to a new given width and height.
Image & Crop (int offsetX, int offsetY, int newWidth, int newHeight)
Crop an image to area defined by a rectangle.
Image & Dither (int rBpp, int gBpp, int bBpp, int aBpp)
Dither image data to 16bpp or lower (Floyd-Steinberg dithering)
void Draw (const ::Image &src, ::Rectangle srcRec, ::Rectangle dstRec, ::Color tint={255, 255, 255, 255})
void DrawCircle (::Vector2 center, int radius, ::Color color={255, 255, 255, 255})
void DrawCircle (int centerX, int centerY, int radius, ::Color color={255, 255, 255, 255})
void DrawLine (::Vector2 start, ::Vector2 end, ::Color color={255, 255, 255, 255})
void DrawLine (::Vector2 start, ::Vector2 end, int thick, ::Color color={255, 255, 255, 255})
Description: Draw a line defining thickness within an image.
void DrawLine (int startPosX, int startPosY, int endPosX, int endPosY, ::Color color={255, 255, 255, 255})
void DrawPixel (::Vector2 position, ::Color color={255, 255, 255, 255})
void DrawPixel (int posX, int posY, ::Color color={255, 255, 255, 255})
Draw pixel within an image.
void DrawRectangle (::Rectangle rec, ::Color color={255, 255, 255, 255})
void DrawRectangle (int posX, int posY, int width, int height, ::Color color={255, 255, 255, 255})
void DrawRectangle (Vector2 position, Vector2 size, ::Color color={255, 255, 255, 255})
void DrawRectangleLines (::Rectangle rec, int thick=1, ::Color color={255, 255, 255, 255})
void DrawText (const ::Font &font, const char *text, ::Vector2 position, float fontSize, float spacing, ::Color tint={255, 255, 255, 255})
void DrawText (const ::Font &font, const std::string &text, ::Vector2 position, float fontSize, float spacing, ::Color tint={255, 255, 255, 255})
void DrawText (const char *text, ::Vector2 position, int fontSize, ::Color color={255, 255, 255, 255})
void DrawText (const char *text, int x, int y, int fontSize, ::Color color={255, 255, 255, 255})
void DrawText (const std::string &text, ::Vector2 position, int fontSize, ::Color color={255, 255, 255, 255})
void DrawText (const std::string &text, int x, int y, int fontSize, ::Color color={255, 255, 255, 255})
void Export (const std::string &fileName) const
Export image data to file, returns true on success.
void ExportAsCode (const std::string &fileName) const
Export image as code file defining an array of bytes, returns true on success.
unsigned char * ExportToMemory (const char *fileType, int *fileSize)
Export image to memory buffer.
Image & FlipHorizontal ()
Flip image horizontally.
Image & FlipVertical ()
Flip image vertically.
Image & Format (int newFormat)
Convert image data to desired format.
::Image FromImage (::Rectangle rec) const
Create an image from another image piece.
Rectangle GetAlphaBorder (float threshold) const
Get image alpha border rectangle.
raylib::Color GetColor (::Vector2 position) const
Get image pixel color at vector position.
raylib::Color GetColor (int x=0, int y=0) const
Get image pixel color at (x, y) position.
void * GetData () const
Retrieves the data value for the object.
int GetFormat () const
Retrieves the format value for the object.
int GetHeight () const
Retrieves the height value for the object.
int GetMipmaps () const
Retrieves the mipmaps value for the object.
int GetPixelDataSize () const
Returns the pixel data size based on the current image.
::Vector2 GetSize () const
Retrieve the width and height of the image.
int GetWidth () const
Retrieves the width value for the object.
bool IsValid () const
Retrieve whether or not the Image has been loaded.
void KernelConvolution (const float *kernel, int kernelSize)
Apply custom square convolution kernel to image.
void Load (const ::Texture2D &texture)
Load an image from the given file.
void Load (const std::string &fileName)
Load image from file into CPU memory (RAM)
void Load (const std::string &fileName, int *frames)
Load image sequence from file (frames appended to image.data).
void Load (const std::string &fileName, int width, int height, int format, int headerSize)
Load image from RAW file data.
void Load (const std::string &fileType, const unsigned char *fileData, int dataSize)
Load image from memory buffer, fileType refers to extension: i.e.
::Color * LoadColors () const
Load color data from image as a Color array (RGBA - 32bit)
::Color * LoadPalette (int maxPaletteSize, int *colorsCount) const
Load colors palette from image as a Color array (RGBA - 32bit)
::Texture2D LoadTexture () const
Load texture from image data.
Image & Mipmaps ()
Generate all mipmap levels for a provided image.
operator::Texture2D () const
Loads a texture from the image data.
Image & operator= (const ::Image &image)
Image & operator= (const Image &other)
Image & operator= (Image &&other) noexcept
Image & Resize (int newWidth, int newHeight)
Resize and image to new size.
Image & ResizeCanvas (int newWidth, int newHeight, int offsetX=0, int offsetY=0, ::Color color={255, 255, 255, 255})
Resize canvas and fill with color.
Image & ResizeNN (int newWidth, int newHeight)
Resize and image to new size using Nearest-Neighbor scaling algorithm.
Image & Rotate (int degrees)
Rotate image by input angle in degrees (-359 to 359)
Image & RotateCCW ()
Rotate image counter-clockwise 90deg.
Image & RotateCW ()
Rotate image clockwise 90deg.
void SetHeight (int height, int offsetX=0, int offsetY=0, ::Color fill={255, 255, 255, 255})
Set the height of the image canvas.
void SetWidth (int width, int offsetX=0, int offsetY=0, ::Color fill={255, 255, 255, 255})
Set the width of the image canvas.
Image & ToPOT (::Color fillColor)
Convert image to POT (power-of-two)
void Unload ()
Unload image from CPU memory (RAM)
void UnloadColors (::Color *colors) const
Unload color data loaded with LoadImageColors()
void UnloadPalette (::Color *colors) const
Unload colors palette loaded with LoadImagePalette()
Static Public Member Functions
::Image Cellular (int width, int height, int tileSize)
Generate image: cellular algorithm.
::Image Checked (int width, int height, int checksX, int checksY, ::Color col1={255, 255, 255, 255}, ::Color col2={0, 0, 0, 255})
Generate image: checked.
::Image Color (int width, int height, ::Color color={255, 255, 255, 255})
Generate image: plain color.
::Image GetClipboard ()
Get clipboard image content.
static int GetPixelDataSize (int width, int height, int format=PIXELFORMAT_UNCOMPRESSED_R32G32B32A32)
Get pixel data size in bytes for certain format.
::Image GradientLinear (int width, int height, int direction, ::Color start, ::Color end)
Generate image: linear gradient.
::Image GradientRadial (int width, int height, float density, ::Color inner, ::Color outer)
Generate image: radial gradient.
::Image LoadFromScreen ()
Get pixel data from screen buffer and return an Image (screenshot)
::Image Text (const ::Font &font, const std::string &text, float fontSize, float spacing, ::Color tint={255, 255, 255, 255})
::Image Text (const std::string &text, int fontSize, ::Color color={255, 255, 255, 255})
::Image WhiteNoise (int width, int height, float factor)
Generate image: white noise.
Protected Member Functions
void set (const ::Image &image)
Detailed Description
Image type, bpp always RGBA (32bit)
Data stored in CPU memory (RAM)
Definition at line 17 of file Image.hpp.
Constructor & Destructor Documentation
Image() [1/12]
raylib::Image::Image (void * data = nullptr, int width = 0, int height = 0, int mipmaps = 1, int format = PIXELFORMAT_UNCOMPRESSED_R8G8B8A8) inline
Definition at line 19 of file Image.hpp.
Image() [2/12]
raylib::Image::Image (const ::Image & image) inline
Definition at line 29 of file Image.hpp.
Image() [3/12]
raylib::Image::Image (const std::string & fileName) inline
Load an image from the given file.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
See also
Load()
Definition at line 38 of file Image.hpp.
References Load().
Image() [4/12]
raylib::Image::Image (const std::string & fileName, int width, int height, int format, int headerSize = 0) inline
Load a raw image from the given file, with the provided width, height, and formats.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
See also
LoadRaw()
Definition at line 47 of file Image.hpp.
References Load().
Image() [5/12]
raylib::Image::Image (const std::string & fileName, int * frames) inline
Load an animation image from the given file.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
See also
LoadAnim()
Definition at line 58 of file Image.hpp.
References Load().
Image() [6/12]
raylib::Image::Image (const std::string & fileType, const unsigned char * fileData, int dataSize) inline
Load an image from the given file.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
Definition at line 65 of file Image.hpp.
References Load().
Image() [7/12]
raylib::Image::Image (const ::Texture2D & texture) inline
Load an image from the given file.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
Definition at line 74 of file Image.hpp.
References Load().
Image() [8/12]
raylib::Image::Image (int width, int height, ::Color color = {255, 255, 255, 255}) inline
Definition at line 76 of file Image.hpp.
Image() [9/12]
raylib::Image::Image (const std::string & text, int fontSize, ::Color color = {255, 255, 255, 255}) inline
Definition at line 78 of file Image.hpp.
Image() [10/12]
raylib::Image::Image (const ::Font & font, const std::string & text, float fontSize, float spacing, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 82 of file Image.hpp.
Image() [11/12]
raylib::Image::Image (const Image & other) inline
Definition at line 91 of file Image.hpp.
Image() [12/12]
raylib::Image::Image (Image && other) inline noexcept
Definition at line 93 of file Image.hpp.
~Image()
raylib::Image::~Image () inline
Definition at line 172 of file Image.hpp.
Member Function Documentation
AlphaClear()
Image & raylib::Image::AlphaClear (::Color color, float threshold) inline
Clear alpha channel to desired color.
Definition at line 390 of file Image.hpp.
AlphaCrop()
Image & raylib::Image::AlphaCrop (float threshold) inline
Crop image depending on alpha value.
Definition at line 382 of file Image.hpp.
AlphaMask()
Image & raylib::Image::AlphaMask (const ::Image & alphaMask) inline
Apply alpha mask to image.
Definition at line 398 of file Image.hpp.
AlphaPremultiply()
Image & raylib::Image::AlphaPremultiply () inline
Premultiply alpha channel.
Definition at line 406 of file Image.hpp.
Cellular()
::Image raylib::Image::Cellular (int width, int height, int tileSize) inline static
Generate image: cellular algorithm.
Bigger tileSize means bigger cells
Definition at line 165 of file Image.hpp.
Channel()
::Image raylib::Image::Channel (int selectedChannel) inline
Create an image from a selected channel of another image (GRAYSCALE)
Definition at line 750 of file Image.hpp.
Checked()
::Image raylib::Image::Checked (int width, int height, int checksX, int checksY, ::Color col1 = {255, 255, 255, 255}, ::Color col2 = {0, 0, 0, 255}) inline static
Generate image: checked.
Definition at line 145 of file Image.hpp.
ClearBackground()
Image & raylib::Image::ClearBackground (::Color color = {0, 0, 0, 255}) inline
Clear image background with given color.
Definition at line 589 of file Image.hpp.
Color()
::Image raylib::Image::Color (int width, int height, ::Color color = {255, 255, 255, 255}) inline static
Generate image: plain color.
Definition at line 124 of file Image.hpp.
ColorBrightness()
Image & raylib::Image::ColorBrightness (int brightness) inline
Modify image color: brightness.
Parameters
brightness Brightness values between -255 and 255
Definition at line 554 of file Image.hpp.
ColorContrast()
Image & raylib::Image::ColorContrast (float contrast) inline
Modify image color: contrast.
Parameters
contrast Contrast values between -100 and 100
Definition at line 544 of file Image.hpp.
ColorGrayscale()
Image & raylib::Image::ColorGrayscale () inline
Modify image color: grayscale.
Definition at line 534 of file Image.hpp.
ColorInvert()
Image & raylib::Image::ColorInvert () inline
Modify image color: invert.
Definition at line 526 of file Image.hpp.
ColorReplace()
Image & raylib::Image::ColorReplace (::Color color, ::Color replace) inline
Modify image color: replace color.
Definition at line 562 of file Image.hpp.
ColorTint()
Image & raylib::Image::ColorTint (::Color color = {255, 255, 255, 255}) inline
Modify image color: tint.
Definition at line 518 of file Image.hpp.
Copy()
::Image raylib::Image::Copy () const inline
Create an image duplicate (useful for transformations)
Definition at line 348 of file Image.hpp.
Crop() [1/4]
Image & raylib::Image::Crop (::Rectangle crop) inline
Crop an image to area defined by a rectangle.
Definition at line 374 of file Image.hpp.
Crop() [2/4]
Image & raylib::Image::Crop (::Vector2 size) inline
Crop an image to a new given width and height based on a vector.
Definition at line 419 of file Image.hpp.
References Crop().
Referenced by Crop().
Crop() [3/4]
Image & raylib::Image::Crop (int newWidth, int newHeight) inline
Crop an image to a new given width and height.
Definition at line 414 of file Image.hpp.
References Crop().
Referenced by Crop().
Crop() [4/4]
Image & raylib::Image::Crop (int offsetX, int offsetY, int newWidth, int newHeight) inline
Crop an image to area defined by a rectangle.
Definition at line 424 of file Image.hpp.
Dither()
Image & raylib::Image::Dither (int rBpp, int gBpp, int bBpp, int aBpp) inline
Dither image data to 16bpp or lower (Floyd-Steinberg dithering)
Definition at line 470 of file Image.hpp.
Draw()
void raylib::Image::Draw (const ::Image & src, ::Rectangle srcRec, ::Rectangle dstRec, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 646 of file Image.hpp.
DrawCircle() [1/2]
void raylib::Image::DrawCircle (::Vector2 center, int radius, ::Color color = {255, 255, 255, 255}) inline
Definition at line 624 of file Image.hpp.
DrawCircle() [2/2]
void raylib::Image::DrawCircle (int centerX, int centerY, int radius, ::Color color = {255, 255, 255, 255}) inline
Definition at line 620 of file Image.hpp.
DrawLine() [1/3]
void raylib::Image::DrawLine (::Vector2 start, ::Vector2 end, ::Color color = {255, 255, 255, 255}) inline
Definition at line 609 of file Image.hpp.
DrawLine() [2/3]
void raylib::Image::DrawLine (::Vector2 start, ::Vector2 end, int thick, ::Color color = {255, 255, 255, 255}) inline
Description: Draw a line defining thickness within an image.
Definition at line 616 of file Image.hpp.
DrawLine() [3/3]
void raylib::Image::DrawLine (int startPosX, int startPosY, int endPosX, int endPosY, ::Color color = {255, 255, 255, 255}) inline
Definition at line 605 of file Image.hpp.
DrawPixel() [1/2]
void raylib::Image::DrawPixel (::Vector2 position, ::Color color = {255, 255, 255, 255}) inline
Definition at line 601 of file Image.hpp.
DrawPixel() [2/2]
void raylib::Image::DrawPixel (int posX, int posY, ::Color color = {255, 255, 255, 255}) inline
Draw pixel within an image.
Definition at line 597 of file Image.hpp.
DrawRectangle() [1/3]
void raylib::Image::DrawRectangle (::Rectangle rec, ::Color color = {255, 255, 255, 255}) inline
Definition at line 636 of file Image.hpp.
DrawRectangle() [2/3]
void raylib::Image::DrawRectangle (int posX, int posY, int width, int height, ::Color color = {255, 255, 255, 255}) inline
Definition at line 628 of file Image.hpp.
DrawRectangle() [3/3]
void raylib::Image::DrawRectangle (Vector2 position, Vector2 size, ::Color color = {255, 255, 255, 255}) inline
Definition at line 632 of file Image.hpp.
DrawRectangleLines()
void raylib::Image::DrawRectangleLines (::Rectangle rec, int thick = 1, ::Color color = {255, 255, 255, 255}) inline
Definition at line 640 of file Image.hpp.
DrawText() [1/6]
void raylib::Image::DrawText (const ::Font & font, const char * text, ::Vector2 position, float fontSize, float spacing, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 682 of file Image.hpp.
DrawText() [2/6]
void raylib::Image::DrawText (const ::Font & font, const std::string & text, ::Vector2 position, float fontSize, float spacing, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 672 of file Image.hpp.
DrawText() [3/6]
void raylib::Image::DrawText (const char * text, ::Vector2 position, int fontSize, ::Color color = {255, 255, 255, 255}) inline
Definition at line 650 of file Image.hpp.
DrawText() [4/6]
void raylib::Image::DrawText (const char * text, int x, int y, int fontSize, ::Color color = {255, 255, 255, 255}) inline
Definition at line 668 of file Image.hpp.
DrawText() [5/6]
void raylib::Image::DrawText (const std::string & text, ::Vector2 position, int fontSize, ::Color color = {255, 255, 255, 255}) inline
Definition at line 654 of file Image.hpp.
DrawText() [6/6]
void raylib::Image::DrawText (const std::string & text, int x, int y, int fontSize, ::Color color = {255, 255, 255, 255}) inline
Definition at line 664 of file Image.hpp.
Export()
void raylib::Image::Export (const std::string & fileName) const inline
Export image data to file, returns true on success.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
Definition at line 292 of file Image.hpp.
References raylib::ExportImage().
ExportAsCode()
void raylib::Image::ExportAsCode (const std::string & fileName) const inline
Export image as code file defining an array of bytes, returns true on success.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
Definition at line 310 of file Image.hpp.
References raylib::ExportImageAsCode().
ExportToMemory()
unsigned char * raylib::Image::ExportToMemory (const char * fileType, int * fileSize) inline
Export image to memory buffer.
Definition at line 301 of file Image.hpp.
FlipHorizontal()
Image & raylib::Image::FlipHorizontal () inline
Flip image horizontally.
Definition at line 486 of file Image.hpp.
FlipVertical()
Image & raylib::Image::FlipVertical () inline
Flip image vertically.
Definition at line 478 of file Image.hpp.
Format()
Image & raylib::Image::Format (int newFormat) inline
Convert image data to desired format.
Definition at line 358 of file Image.hpp.
FromImage()
::Image raylib::Image::FromImage (::Rectangle rec) const inline
Create an image from another image piece.
Definition at line 353 of file Image.hpp.
GetAlphaBorder()
Rectangle raylib::Image::GetAlphaBorder (float threshold) const inline
Get image alpha border rectangle.
Parameters
threshold Threshold is defined as a percentatge: 0.0f -> 1.0f
Definition at line 572 of file Image.hpp.
GetClipboard()
::Image raylib::Image::GetClipboard () inline static
Get clipboard image content.
Definition at line 170 of file Image.hpp.
GetColor() [1/2]
raylib::Color raylib::Image::GetColor (::Vector2 position) const inline
Get image pixel color at vector position.
Definition at line 582 of file Image.hpp.
GetColor() [2/2]
raylib::Color raylib::Image::GetColor (int x = 0, int y = 0) const inline
Get image pixel color at (x, y) position.
Definition at line 577 of file Image.hpp.
GetData()
void * raylib::Image::GetData () const inline
Retrieves the data value for the object.
Returns
The data value of the object.
Definition at line 316 of file Image.hpp.
GetFormat()
int raylib::Image::GetFormat () const inline
Retrieves the format value for the object.
Returns
The format value of the object.
Definition at line 320 of file Image.hpp.
GetHeight()
int raylib::Image::GetHeight () const inline
Retrieves the height value for the object.
Returns
The height value of the object.
Definition at line 318 of file Image.hpp.
GetMipmaps()
int raylib::Image::GetMipmaps () const inline
Retrieves the mipmaps value for the object.
Returns
The mipmaps value of the object.
Definition at line 319 of file Image.hpp.
GetPixelDataSize() [1/2]
int raylib::Image::GetPixelDataSize () const inline
Returns the pixel data size based on the current image.
Returns
The pixel data size of the image.
Definition at line 738 of file Image.hpp.
GetPixelDataSize() [2/2]
static int raylib::Image::GetPixelDataSize (int width, int height, int format = PIXELFORMAT_UNCOMPRESSED_R32G32B32A32) inline static
Get pixel data size in bytes for certain format.
Definition at line 729 of file Image.hpp.
GetSize()
::Vector2 raylib::Image::GetSize () const inline
Retrieve the width and height of the image.
Definition at line 343 of file Image.hpp.
GetWidth()
int raylib::Image::GetWidth () const inline
Retrieves the width value for the object.
Returns
The width value of the object.
Definition at line 317 of file Image.hpp.
GradientLinear()
::Image raylib::Image::GradientLinear (int width, int height, int direction, ::Color start, ::Color end) inline static
Generate image: linear gradient.
Definition at line 131 of file Image.hpp.
GradientRadial()
::Image raylib::Image::GradientRadial (int width, int height, float density, ::Color inner, ::Color outer) inline static
Generate image: radial gradient.
Definition at line 138 of file Image.hpp.
IsValid()
bool raylib::Image::IsValid () const inline
Retrieve whether or not the Image has been loaded.
Returns
True or false depending on whether the Image has been loaded.
Definition at line 745 of file Image.hpp.
Referenced by Load(), Load(), Load(), Load(), and Load().
KernelConvolution()
void raylib::Image::KernelConvolution (const float * kernel, int kernelSize) inline
Apply custom square convolution kernel to image.
Definition at line 755 of file Image.hpp.
Load() [1/5]
void raylib::Image::Load (const ::Texture2D & texture) inline
Load an image from the given file.
Exceptions
raylib::RaylibException Thrown if the image animation to load from the file.
See also
::LoadImageFromTexture()
Definition at line 270 of file Image.hpp.
References IsValid().
Load() [2/5]
void raylib::Image::Load (const std::string & fileName) inline
Load image from file into CPU memory (RAM)
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
See also
LoadImage()
Definition at line 214 of file Image.hpp.
References IsValid(), and raylib::LoadImage().
Referenced by Image(), Image(), Image(), Image(), and Image().
Load() [3/5]
void raylib::Image::Load (const std::string & fileName, int * frames) inline
Load image sequence from file (frames appended to image.data).
Exceptions
raylib::RaylibException Thrown if the image animation to load from the file.
See also
LoadImageAnim()
Definition at line 242 of file Image.hpp.
References IsValid(), and raylib::LoadImageAnim().
Load() [4/5]
void raylib::Image::Load (const std::string & fileName, int width, int height, int format, int headerSize) inline
Load image from RAW file data.
Exceptions
raylib::RaylibException Thrown if the image failed to load from the file.
See also
LoadImageRaw()
Definition at line 228 of file Image.hpp.
References IsValid(), and raylib::LoadImageRaw().
Load() [5/5]
void raylib::Image::Load (const std::string & fileType, const unsigned char * fileData, int dataSize) inline
Load image from memory buffer, fileType refers to extension: i.e.
"png".
Exceptions
raylib::RaylibException Thrown if the image animation to load from the file.
See also
LoadImageFromMemory()
Definition at line 256 of file Image.hpp.
References IsValid(), and raylib::LoadImageFromMemory().
LoadColors()
::Color * raylib::Image::LoadColors () const inline
Load color data from image as a Color array (RGBA - 32bit)
Definition at line 695 of file Image.hpp.
LoadFromScreen()
::Image raylib::Image::LoadFromScreen () inline static
Get pixel data from screen buffer and return an Image (screenshot)
Definition at line 119 of file Image.hpp.
LoadPalette()
::Color * raylib::Image::LoadPalette (int maxPaletteSize, int * colorsCount) const inline
Load colors palette from image as a Color array (RGBA - 32bit)
Definition at line 700 of file Image.hpp.
LoadTexture()
::Texture2D raylib::Image::LoadTexture () const inline
Load texture from image data.
Definition at line 717 of file Image.hpp.
Referenced by operator::Texture2D().
Mipmaps()
Image & raylib::Image::Mipmaps () inline
Generate all mipmap levels for a provided image.
Definition at line 462 of file Image.hpp.
operator::Texture2D()
raylib::Image::operator::Texture2D () const inline
Loads a texture from the image data.
See also
LoadTexture()
Definition at line 724 of file Image.hpp.
References LoadTexture().
operator=() [1/3]
Image & raylib::Image::operator= (const ::Image & image) inline
Definition at line 174 of file Image.hpp.
operator=() [2/3]
Image & raylib::Image::operator= (const Image & other) inline
Definition at line 179 of file Image.hpp.
operator=() [3/3]
Image & raylib::Image::operator= (Image && other) inline noexcept
Definition at line 190 of file Image.hpp.
Resize()
Image & raylib::Image::Resize (int newWidth, int newHeight) inline
Resize and image to new size.
Definition at line 437 of file Image.hpp.
ResizeCanvas()
Image & raylib::Image::ResizeCanvas (int newWidth, int newHeight, int offsetX = 0, int offsetY = 0, ::Color color = {255, 255, 255, 255}) inline
Resize canvas and fill with color.
Definition at line 454 of file Image.hpp.
ResizeNN()
Image & raylib::Image::ResizeNN (int newWidth, int newHeight) inline
Resize and image to new size using Nearest-Neighbor scaling algorithm.
Definition at line 445 of file Image.hpp.
Rotate()
Image & raylib::Image::Rotate (int degrees) inline
Rotate image by input angle in degrees (-359 to 359)
Definition at line 494 of file Image.hpp.
RotateCCW()
Image & raylib::Image::RotateCCW () inline
Rotate image counter-clockwise 90deg.
Definition at line 510 of file Image.hpp.
RotateCW()
Image & raylib::Image::RotateCW () inline
Rotate image clockwise 90deg.
Definition at line 502 of file Image.hpp.
set()
void raylib::Image::set (const ::Image & image) inline protected
Definition at line 759 of file Image.hpp.
SetHeight()
void raylib::Image::SetHeight (int height, int offsetX = 0, int offsetY = 0, ::Color fill = {255, 255, 255, 255}) inline
Set the height of the image canvas.
See also
ResizeCanvas
Definition at line 336 of file Image.hpp.
SetWidth()
void raylib::Image::SetWidth (int width, int offsetX = 0, int offsetY = 0, ::Color fill = {255, 255, 255, 255}) inline
Set the width of the image canvas.
See also
ResizeCanvas
Definition at line 327 of file Image.hpp.
Text() [1/2]
::Image raylib::Image::Text (const ::Font & font, const std::string & text, float fontSize, float spacing, ::Color tint = {255, 255, 255, 255}) inline static
Definition at line 107 of file Image.hpp.
Text() [2/2]
::Image raylib::Image::Text (const std::string & text, int fontSize, ::Color color = {255, 255, 255, 255}) inline static
Definition at line 103 of file Image.hpp.
ToPOT()
Image & raylib::Image::ToPOT (::Color fillColor) inline
Convert image to POT (power-of-two)
Definition at line 366 of file Image.hpp.
Unload()
void raylib::Image::Unload () inline
Unload image from CPU memory (RAM)
Definition at line 280 of file Image.hpp.
UnloadColors()
void raylib::Image::UnloadColors (::Color * colors) const inline
Unload color data loaded with LoadImageColors()
Definition at line 707 of file Image.hpp.
UnloadPalette()
void raylib::Image::UnloadPalette (::Color * colors) const inline
Unload colors palette loaded with LoadImagePalette()
Definition at line 712 of file Image.hpp.
WhiteNoise()
::Image raylib::Image::WhiteNoise (int width, int height, float factor) inline static
Generate image: white noise.
Definition at line 158 of file Image.hpp.