raylib-cpp: raylib::AudioStream Class Reference
raylib::AudioStream Class Reference
AudioStream management functions.
#include <AudioStream.hpp>
Public Member Functions
AudioStream (AudioStream &&other) noexcept
AudioStream (const ::AudioStream &music)
AudioStream (const AudioStream &)=delete
AudioStream (rAudioBuffer *buffer=nullptr, rAudioProcessor *processor=nullptr, unsigned int sampleRate=0, unsigned int sampleSize=0, unsigned int channels=0)
AudioStream (unsigned int sampleRate, unsigned int sampleSize, unsigned int channels=2)
Init audio stream (to stream raw audio pcm data)
void AttachProcessor (::AudioCallback processor)
Attach audio stream processor to stream.
void DetachProcessor (::AudioCallback processor)
Detach audio stream processor from stream.
rAudioBuffer * GetBuffer () const
Retrieves the buffer value for the object.
unsigned int GetChannels () const
Retrieves the channels value for the object.
rAudioProcessor * GetProcessor () const
Retrieves the processor value for the object.
unsigned int GetSampleRate () const
Retrieves the sampleRate value for the object.
unsigned int GetSampleSize () const
Retrieves the sampleSize value for the object.
bool IsPlaying () const
Check if audio stream is playing.
bool IsProcessed () const
Check if any audio stream buffers requires refill.
bool IsValid () const
Retrieve whether or not the audio stream is ready.
void Load (unsigned int SampleRate, unsigned int SampleSize, unsigned int Channels=2)
Load audio stream (to stream raw audio pcm data)
AudioStream & operator= (AudioStream &&other) noexcept
AudioStream & operator= (const ::AudioStream &stream)
AudioStream & operator= (const AudioStream &)=delete
AudioStream & Pause ()
Pause audio stream.
AudioStream & Play ()
Play audio stream.
AudioStream & Resume ()
Resume audio stream.
void SetCallback (::AudioCallback callback)
Audio thread callback to request new data.
AudioStream & SetPan (float pan=0.5f)
Set pan for audio stream (0.5 is centered)
AudioStream & SetPitch (float pitch)
Set pitch for audio stream (1.0 is base level)
AudioStream & SetVolume (float volume=1.0f)
Set volume for audio stream (1.0 is max level)
AudioStream & Stop ()
Stop audio stream.
void Unload ()
Unload audio stream and free memory.
AudioStream & Update (const void *data, int samplesCount)
Update audio stream buffers with data.
Static Public Member Functions
static void SetBufferSizeDefault (int size)
Default size for new audio streams.
Protected Member Functions
void set (const ::AudioStream &stream)
Detailed Description
AudioStream management functions.
Definition at line 12 of file AudioStream.hpp.
Constructor & Destructor Documentation
AudioStream() [1/4]
raylib::AudioStream::AudioStream (const ::AudioStream & music) inline
Definition at line 14 of file AudioStream.hpp.
AudioStream() [2/4]
raylib::AudioStream::AudioStream (rAudioBuffer * buffer = nullptr, rAudioProcessor * processor = nullptr, unsigned int sampleRate = 0, unsigned int sampleSize = 0, unsigned int channels = 0) inline
Definition at line 19 of file AudioStream.hpp.
AudioStream() [3/4]
raylib::AudioStream::AudioStream (unsigned int sampleRate, unsigned int sampleSize, unsigned int channels = 2) inline
Init audio stream (to stream raw audio pcm data)
Exceptions
raylib::RaylibException Throws if the AudioStream failed to load.
Definition at line 34 of file AudioStream.hpp.
References Load().
AudioStream() [4/4]
raylib::AudioStream::AudioStream (AudioStream && other) inline noexcept
Definition at line 40 of file AudioStream.hpp.
~AudioStream()
raylib::AudioStream::~AudioStream () inline
Definition at line 50 of file AudioStream.hpp.
Member Function Documentation
AttachProcessor()
void raylib::AudioStream::AttachProcessor (::AudioCallback processor) inline
Attach audio stream processor to stream.
Definition at line 178 of file AudioStream.hpp.
DetachProcessor()
void raylib::AudioStream::DetachProcessor (::AudioCallback processor) inline
Detach audio stream processor from stream.
Definition at line 183 of file AudioStream.hpp.
GetBuffer()
rAudioBuffer * raylib::AudioStream::GetBuffer () const inline
Retrieves the buffer value for the object.
Returns
The buffer value of the object.
Definition at line 52 of file AudioStream.hpp.
GetChannels()
unsigned int raylib::AudioStream::GetChannels () const inline
Retrieves the channels value for the object.
Returns
The channels value of the object.
Definition at line 56 of file AudioStream.hpp.
GetProcessor()
rAudioProcessor * raylib::AudioStream::GetProcessor () const inline
Retrieves the processor value for the object.
Returns
The processor value of the object.
Definition at line 53 of file AudioStream.hpp.
GetSampleRate()
unsigned int raylib::AudioStream::GetSampleRate () const inline
Retrieves the sampleRate value for the object.
Returns
The sampleRate value of the object.
Definition at line 54 of file AudioStream.hpp.
GetSampleSize()
unsigned int raylib::AudioStream::GetSampleSize () const inline
Retrieves the sampleSize value for the object.
Returns
The sampleSize value of the object.
Definition at line 55 of file AudioStream.hpp.
IsPlaying()
bool raylib::AudioStream::IsPlaying () const inline
Check if audio stream is playing.
Definition at line 131 of file AudioStream.hpp.
IsProcessed()
bool raylib::AudioStream::IsProcessed () const inline
Check if any audio stream buffers requires refill.
Definition at line 102 of file AudioStream.hpp.
IsValid()
bool raylib::AudioStream::IsValid () const inline
Retrieve whether or not the audio stream is ready.
Definition at line 188 of file AudioStream.hpp.
Referenced by Load(), and Unload().
Load()
void raylib::AudioStream::Load (unsigned int SampleRate, unsigned int SampleSize, unsigned int Channels = 2) inline
Load audio stream (to stream raw audio pcm data)
Exceptions
raylib::RaylibException Throws if the AudioStream failed to load.
Definition at line 195 of file AudioStream.hpp.
References IsValid(), and Unload().
Referenced by AudioStream().
operator=() [1/2]
AudioStream & raylib::AudioStream::operator= (AudioStream && other) inline noexcept
Definition at line 65 of file AudioStream.hpp.
operator=() [2/2]
AudioStream & raylib::AudioStream::operator= (const ::AudioStream & stream) inline
Definition at line 58 of file AudioStream.hpp.
Pause()
AudioStream & raylib::AudioStream::Pause () inline
Pause audio stream.
Definition at line 115 of file AudioStream.hpp.
Play()
AudioStream & raylib::AudioStream::Play () inline
Play audio stream.
Definition at line 107 of file AudioStream.hpp.
Resume()
AudioStream & raylib::AudioStream::Resume () inline
Resume audio stream.
Definition at line 123 of file AudioStream.hpp.
set()
void raylib::AudioStream::set (const ::AudioStream & stream) inline protected
Definition at line 203 of file AudioStream.hpp.
SetBufferSizeDefault()
static void raylib::AudioStream::SetBufferSizeDefault (int size) inline static
Default size for new audio streams.
Definition at line 168 of file AudioStream.hpp.
SetCallback()
void raylib::AudioStream::SetCallback (::AudioCallback callback) inline
Audio thread callback to request new data.
Definition at line 173 of file AudioStream.hpp.
SetPan()
AudioStream & raylib::AudioStream::SetPan (float pan = 0.5f) inline
Set pan for audio stream (0.5 is centered)
Definition at line 160 of file AudioStream.hpp.
SetPitch()
AudioStream & raylib::AudioStream::SetPitch (float pitch) inline
Set pitch for audio stream (1.0 is base level)
Definition at line 152 of file AudioStream.hpp.
SetVolume()
AudioStream & raylib::AudioStream::SetVolume (float volume = 1.0f) inline
Set volume for audio stream (1.0 is max level)
Definition at line 144 of file AudioStream.hpp.
Stop()
AudioStream & raylib::AudioStream::Stop () inline
Stop audio stream.
Definition at line 136 of file AudioStream.hpp.
Unload()
void raylib::AudioStream::Unload () inline
Unload audio stream and free memory.
Definition at line 93 of file AudioStream.hpp.
References IsValid().
Referenced by Load().
Update()
AudioStream & raylib::AudioStream::Update (const void * data, int samplesCount) inline
Update audio stream buffers with data.
Definition at line 85 of file AudioStream.hpp.