raylib-cpp: raylib::Material Class Reference
raylib::Material Class Reference
Material type (generic)
#include <Material.hpp>
Public Member Functions
Material ()
Load default material (Supports: DIFFUSE, SPECULAR, NORMAL maps)
Material (const ::Material &material)
Material (const Material &)=delete
Material (Material &&other) noexcept
void DrawMesh (const ::Mesh &mesh, ::Matrix *transforms, int instances) const
Draw multiple mesh instances with material and different transforms.
void DrawMesh (const ::Mesh &mesh, ::Matrix transform) const
Draw a 3d mesh with material and transform.
::MaterialMap * GetMaps () const
Retrieves the maps value for the object.
::Shader GetShader () const
Retrieves the shader value for the object.
bool IsValid () const
Check if material is ready.
Material & operator= (const ::Material &material)
Material & operator= (const Material &)=delete
Material & operator= (Material &&other) noexcept
void SetMaps (::MaterialMap *value)
Sets the maps value for the object.
void SetShader (::Shader value)
Sets the shader value for the object.
Material & SetTexture (int mapType, const ::Texture2D &texture)
Set texture for a material map type (MAP_DIFFUSE, MAP_SPECULAR...)
void Unload ()
Unload material from memory.
Static Public Member Functions
static std::vector< Material > Load (const std::string &fileName)
Load materials from model file.
Protected Member Functions
void set (const ::Material &material)
Detailed Description
Material type (generic)
Definition at line 14 of file Material.hpp.
Constructor & Destructor Documentation
Material() [1/3]
raylib::Material::Material (const ::Material & material) inline
Definition at line 16 of file Material.hpp.
Material() [2/3]
raylib::Material::Material () inline
Load default material (Supports: DIFFUSE, SPECULAR, NORMAL maps)
Definition at line 21 of file Material.hpp.
Referenced by Load().
Material() [3/3]
raylib::Material::Material (Material && other) inline noexcept
Definition at line 25 of file Material.hpp.
~Material()
raylib::Material::~Material () inline
Definition at line 36 of file Material.hpp.
Member Function Documentation
DrawMesh() [1/2]
void raylib::Material::DrawMesh (const ::Mesh & mesh, ::Matrix * transforms, int instances) const inline
Draw multiple mesh instances with material and different transforms.
Definition at line 100 of file Material.hpp.
DrawMesh() [2/2]
void raylib::Material::DrawMesh (const ::Mesh & mesh, ::Matrix transform) const inline
Draw a 3d mesh with material and transform.
Definition at line 95 of file Material.hpp.
References DrawMesh().
Referenced by DrawMesh().
GetMaps()
::MaterialMap * raylib::Material::GetMaps () const inline
Retrieves the maps value for the object.
Returns
The maps value of the object.
Definition at line 49 of file Material.hpp.
GetShader()
::Shader raylib::Material::GetShader () const inline
Retrieves the shader value for the object.
Returns
The shader value of the object.
Definition at line 48 of file Material.hpp.
IsValid()
bool raylib::Material::IsValid () const inline
Check if material is ready.
Definition at line 107 of file Material.hpp.
Load()
static std::vector< Material > raylib::Material::Load (const std::string & fileName) inline static
Load materials from model file.
Definition at line 41 of file Material.hpp.
References Material().
operator=() [1/2]
Material & raylib::Material::operator= (const ::Material & material) inline
Definition at line 53 of file Material.hpp.
operator=() [2/2]
Material & raylib::Material::operator= (Material && other) inline noexcept
Definition at line 60 of file Material.hpp.
set()
void raylib::Material::set (const ::Material & material) inline protected
Definition at line 109 of file Material.hpp.
SetMaps()
void raylib::Material::SetMaps (::MaterialMap * value) inline
Sets the maps value for the object.
Parameters
value The value of which to set maps to.
Definition at line 49 of file Material.hpp.
SetShader()
void raylib::Material::SetShader (::Shader value) inline
Sets the shader value for the object.
Parameters
value The value of which to set shader to.
Definition at line 48 of file Material.hpp.
SetTexture()
Material & raylib::Material::SetTexture (int mapType, const ::Texture2D & texture) inline
Set texture for a material map type (MAP_DIFFUSE, MAP_SPECULAR...)
Definition at line 87 of file Material.hpp.
Unload()
void raylib::Material::Unload () inline
Unload material from memory.
Definition at line 77 of file Material.hpp.