raylib-cpp: raylib Namespace Reference
raylib Namespace Reference
All raylib-cpp classes and functions appear in the raylib namespace.
Namespaces
namespace Keyboard
Input-related functions: keyboard.
namespace Mouse
Input-related functions: mouse.
namespace Touch
Input-related functions: touch.
Classes
class AudioDevice
Audio device management functions.
class AudioStream
AudioStream management functions.
class AutomationEventList
AutomationEventList management functions.
class BoundingBox
Bounding box type.
class Camera2D
Camera2D type, defines a 2d camera.
class Camera3D
Camera type, defines a camera position/orientation in 3d space.
class Color
Color type, RGBA (32bit)
class Font
Font type, includes texture and charSet array data.
class Gamepad
Input-related functions: gamepads.
class Image
Image type, bpp always RGBA (32bit)
class Material
Material type (generic)
class Matrix
Matrix type (OpenGL style 4x4 - right handed, column major)
class Mesh
Vertex data defining a mesh.
class MeshUnmanaged
Vertex data defining a mesh, not managed by C++ RAII.
class Model
Model type.
class ModelAnimation
Model animation.
class Music
Music stream type (audio file streaming from memory)
class Ray
Ray type (useful for raycast)
class RayCollision
Raycast hit information.
class RaylibException
Exception used for most raylib-related exceptions.
class Rectangle
Rectangle type.
class RenderTexture
RenderTexture type, for texture rendering.
class Shader
Shader type (generic)
class ShaderUnmanaged
Shader type (generic), not managed by C++ RAII.
class Sound
Wave/Sound management functions.
class Text
Text Functions.
class Texture
Texture type.
class TextureUnmanaged
A Texture that is not managed by C++ RAII.
class Vector2
Vector2 type.
class Vector3
Vector3 type.
class Vector4
Vector4 type.
class VrStereoConfig
VR stereo config functions for VR simulator.
class Wave
Wave type, defines audio wave data.
class Window
Window and Graphics Device Functions.
Typedefs
using Camera = Camera3D
using Quaternion = Vector4
using RenderTexture2D = RenderTexture
using Texture2D = Texture
using Texture2DUnmanaged = TextureUnmanaged
using TextureCubemap = Texture
using TextureCubemapUnmanaged = TextureUnmanaged
Functions
static bool ChangeDirectory (const std::string &dir)
Change working directory, return true on success.
static bool DirectoryExists (const std::string &dirPath)
Check if directory path exists.
static void DrawText (const char *text, int posX, int posY, int fontSize, ::Color color)
Draw text (using default font)
static void DrawText (const std::string &text, int posX, int posY, int fontSize, ::Color color)
Draw text (using default font)
static void DrawTextEx (const Font &font, const char *text, Vector2 position, float fontSize, float spacing, ::Color tint)
Draw text using font and additional parameters.
static void DrawTextEx (const Font &font, const std::string &text, Vector2 position, float fontSize, float spacing, ::Color tint)
Draw text using font and additional parameters.
static void DrawTextPro (const Font &font, const char *text, Vector2 position, Vector2 origin, float rotation, float fontSize, float spacing, ::Color tint)
Draw text using Font and pro parameters (rotation)
static void DrawTextPro (const Font &font, const std::string &text, Vector2 position, Vector2 origin, float rotation, float fontSize, float spacing, ::Color tint)
Draw text using Font and pro parameters (rotation)
static bool ExportImage (const Image &image, const std::string &fileName)
Export image data to file.
static bool ExportImageAsCode (const Image &image, const std::string &fileName)
Export image as code file (.h) defining an array of bytes.
static bool FileExists (const std::string &fileName)
Check if file exists.
static std::string GetClipboardText ()
Get clipboard text content.
static std::string GetDirectoryPath (const std::string &filePath)
Get full path for a given fileName with path.
static std::string GetFileExtension (const std::string &fileName)
Get pointer to extension for a filename string (including point: ".png")
static long GetFileModTime (const std::string &fileName)
Get file modification time (last write time)
static std::string GetFileName (const std::string &filePath)
Get pointer to filename for a path string.
static std::string GetFileNameWithoutExt (const std::string &filePath)
Get filename string without extension.
static std::string GetGamepadName (int gamepad)
Get gamepad internal name id.
static std::string GetMonitorName (int monitor=0)
Get the human-readable, UTF-8 encoded name of the primary monitor.
static std::string GetPrevDirectoryPath (const std::string &dirPath)
Get previous directory path for a given path.
static std::string GetWorkingDirectory ()
Get current working directory.
static void InitWindow (int width, int height, const std::string &title="raylib")
Initialize window and OpenGL context.
static bool IsFileExtension (const std::string &fileName, const std::string &ext)
Check file extension (including point: .png, .wav)
static std::vector< std::string > LoadDirectoryFiles (const std::string &dirPath)
Get filenames in a directory path.
static std::vector< std::string > LoadDirectoryFilesEx (const std::string &basePath, const std::string &filter, bool scanSubdirs=false)
Load directory filepaths with extension filtering and optional subdirectory scanning.
static std::vector< std::string > LoadDroppedFiles ()
Get dropped files names.
static std::string LoadFileText (const std::string &fileName)
Load text data from file (read)
static inline ::Font LoadFont (const std::string &fileName)
Load font from file (filename must include file extension)
static inline ::Font LoadFontEx (const std::string &fileName, int fontSize, const int *codepoints=nullptr, int codepointCount=0)
Load font from file (filename must include file extension)
static inline ::Image LoadImage (const std::string &fileName)
Load an image.
static inline ::Image LoadImageAnim (const std::string &fileName, int *frames)
Load animated image data.
static inline ::Image LoadImageFromMemory (const std::string &fileType, const unsigned char *fileData, int dataSize)
Load image from memory buffer, fileType refers to extension like "png".
static inline ::Image LoadImageRaw (const std::string &fileName, int width, int height, int format, int headerSize)
Load an image from RAW file data.
static int MeasureText (const char *text, int fontSize)
Measure string width for default font.
static int MeasureText (const std::string &text, int fontSize)
Measure string width for default font.
static void OpenURL (const std::string &url)
Open URL with default system browser (if available)
static bool SaveFileText (const std::string &fileName, const std::string &text)
Save text data to file (write)
static void SetClipboardText (const std::string &text)
Set clipboard text content.
static void SetWindowTitle (const std::string &title)
Set title for window.
static void TakeScreenshot (const std::string &fileName)
Takes a screenshot of current screen (saved a .png)
static int TextFindIndex (const std::string &text, const std::string &find)
Find first text occurrence within a string.
static std::string TextInsert (const std::string &text, const std::string &insert, int position)
Insert text in a position.
static bool TextIsEqual (const char *text1, const char *text2)
Check if two text string are equal.
static bool TextIsEqual (const std::string &text1, const std::string &text2)
Check if two text string are equal.
static unsigned int TextLength (const char *text)
Get text length, checks for '\0' ending.
static unsigned int TextLength (const std::string &text)
Get text length, checks for '\0' ending.
static std::string TextReplace (const std::string &text, const std::string &replace, const std::string &by)
Replace text string.
static std::vector< std::string > TextSplit (const std::string &text, char delimiter)
Split text into multiple strings.
static std::string TextSubtext (const std::string &text, int position, int length)
Get a piece of a text string.
static std::string TextToCamel (const std::string &text)
Get Camel case notation version of provided string.
static float TextToFloat (const std::string &text)
Get float value from text.
static int TextToInteger (const std::string &text)
Get integer value from text (negative values not supported)
static std::string TextToLower (const std::string &text)
Get lower case version of provided string.
static std::string TextToPascal (const std::string &text)
Get Pascal case notation version of provided string.
static std::string TextToSnake (const std::string &text)
Get Snake case notation version of provided string.
static std::string TextToUpper (const std::string &text)
Get upper case version of provided string.
Detailed Description
All raylib-cpp classes and functions appear in the raylib namespace.
Typedef Documentation
Camera
using raylib::Camera = typedef Camera3D
Definition at line 130 of file Camera3D.hpp.
Quaternion
using raylib::Quaternion = typedef Vector4
Definition at line 126 of file Vector4.hpp.
RenderTexture2D
using raylib::RenderTexture2D = typedef RenderTexture
Definition at line 121 of file RenderTexture.hpp.
Texture2D
using raylib::Texture2D = typedef Texture
Definition at line 93 of file Texture.hpp.
Texture2DUnmanaged
using raylib::Texture2DUnmanaged = typedef TextureUnmanaged
Definition at line 334 of file TextureUnmanaged.hpp.
TextureCubemap
using raylib::TextureCubemap = typedef Texture
Definition at line 94 of file Texture.hpp.
TextureCubemapUnmanaged
using raylib::TextureCubemapUnmanaged = typedef TextureUnmanaged
Definition at line 335 of file TextureUnmanaged.hpp.
Function Documentation
ChangeDirectory()
static bool raylib::ChangeDirectory (const std::string & dir) inline static
Change working directory, return true on success.
Definition at line 174 of file Functions.hpp.
DirectoryExists()
static bool raylib::DirectoryExists (const std::string & dirPath) inline static
Check if directory path exists.
Definition at line 97 of file Functions.hpp.
DrawText() [1/2]
static void raylib::DrawText (const char * text, int posX, int posY, int fontSize, ::Color color) inline static
Draw text (using default font)
Definition at line 252 of file Functions.hpp.
References DrawText().
Referenced by raylib::Text::Draw(), raylib::Text::Draw(), DrawText(), and DrawText().
DrawText() [2/2]
static void raylib::DrawText (const std::string & text, int posX, int posY, int fontSize, ::Color color) inline static
Draw text (using default font)
Definition at line 260 of file Functions.hpp.
References DrawText().
DrawTextEx() [1/2]
static void raylib::DrawTextEx (const Font & font, const char * text, Vector2 position, float fontSize, float spacing, ::Color tint) inline static
Draw text using font and additional parameters.
Definition at line 268 of file Functions.hpp.
References DrawTextEx().
Referenced by raylib::Text::Draw(), raylib::Text::Draw(), raylib::Text::Draw(), raylib::Font::DrawText(), raylib::Font::DrawText(), raylib::Font::DrawText(), raylib::Font::DrawText(), DrawTextEx(), and DrawTextEx().
DrawTextEx() [2/2]
static void raylib::DrawTextEx (const Font & font, const std::string & text, Vector2 position, float fontSize, float spacing, ::Color tint) inline static
Draw text using font and additional parameters.
Definition at line 276 of file Functions.hpp.
References DrawTextEx().
DrawTextPro() [1/2]
static void raylib::DrawTextPro (const Font & font, const char * text, Vector2 position, Vector2 origin, float rotation, float fontSize, float spacing, ::Color tint) inline static
Draw text using Font and pro parameters (rotation)
Definition at line 283 of file Functions.hpp.
References DrawTextPro().
Referenced by raylib::Text::Draw(), DrawTextPro(), and DrawTextPro().
DrawTextPro() [2/2]
static void raylib::DrawTextPro (const Font & font, const std::string & text, Vector2 position, Vector2 origin, float rotation, float fontSize, float spacing, ::Color tint) inline static
Draw text using Font and pro parameters (rotation)
Definition at line 298 of file Functions.hpp.
References DrawTextPro().
ExportImage()
static bool raylib::ExportImage (const Image & image, const std::string & fileName) inline static
Export image data to file.
Definition at line 238 of file Functions.hpp.
Referenced by raylib::Image::Export().
ExportImageAsCode()
static bool raylib::ExportImageAsCode (const Image & image, const std::string & fileName) inline static
Export image as code file (.h) defining an array of bytes.
Definition at line 245 of file Functions.hpp.
Referenced by raylib::Image::ExportAsCode().
FileExists()
static bool raylib::FileExists (const std::string & fileName) inline static
Check if file exists.
Definition at line 90 of file Functions.hpp.
GetClipboardText()
static std::string raylib::GetClipboardText () inline static
Get clipboard text content.
Definition at line 52 of file Functions.hpp.
GetDirectoryPath()
static std::string raylib::GetDirectoryPath (const std::string & filePath) inline static
Get full path for a given fileName with path.
Definition at line 132 of file Functions.hpp.
GetFileExtension()
static std::string raylib::GetFileExtension (const std::string & fileName) inline static
Get pointer to extension for a filename string (including point: ".png")
Definition at line 111 of file Functions.hpp.
GetFileModTime()
static long raylib::GetFileModTime (const std::string & fileName) inline static
Get file modification time (last write time)
Definition at line 194 of file Functions.hpp.
GetFileName()
static std::string raylib::GetFileName (const std::string & filePath) inline static
Get pointer to filename for a path string.
Definition at line 118 of file Functions.hpp.
GetFileNameWithoutExt()
static std::string raylib::GetFileNameWithoutExt (const std::string & filePath) inline static
Get filename string without extension.
Definition at line 125 of file Functions.hpp.
GetGamepadName()
static std::string raylib::GetGamepadName (int gamepad) inline static
Get gamepad internal name id.
Definition at line 66 of file Functions.hpp.
GetMonitorName()
static std::string raylib::GetMonitorName (int monitor = 0) inline static
Get the human-readable, UTF-8 encoded name of the primary monitor.
Definition at line 38 of file Functions.hpp.
GetPrevDirectoryPath()
static std::string raylib::GetPrevDirectoryPath (const std::string & dirPath) inline static
Get previous directory path for a given path.
Definition at line 139 of file Functions.hpp.
GetWorkingDirectory()
static std::string raylib::GetWorkingDirectory () inline static
Get current working directory.
Definition at line 146 of file Functions.hpp.
InitWindow()
static void raylib::InitWindow (int width, int height, const std::string & title = "raylib") inline static
Initialize window and OpenGL context.
Definition at line 24 of file Functions.hpp.
References InitWindow().
Referenced by raylib::Window::Init(), and InitWindow().
IsFileExtension()
static bool raylib::IsFileExtension (const std::string & fileName, const std::string & ext) inline static
Check file extension (including point: .png, .wav)
Definition at line 104 of file Functions.hpp.
LoadDirectoryFiles()
static std::vector< std::string > raylib::LoadDirectoryFiles (const std::string & dirPath) static
Get filenames in a directory path.
Definition at line 153 of file Functions.hpp.
References LoadDirectoryFiles().
Referenced by LoadDirectoryFiles().
LoadDirectoryFilesEx()
static std::vector< std::string > raylib::LoadDirectoryFilesEx (const std::string & basePath, const std::string & filter, bool scanSubdirs = false) static
Load directory filepaths with extension filtering and optional subdirectory scanning.
Definition at line 164 of file Functions.hpp.
References LoadDirectoryFilesEx().
Referenced by LoadDirectoryFilesEx().
LoadDroppedFiles()
static std::vector< std::string > raylib::LoadDroppedFiles () static
Get dropped files names.
Definition at line 181 of file Functions.hpp.
References LoadDroppedFiles().
Referenced by LoadDroppedFiles().
LoadFileText()
static std::string raylib::LoadFileText (const std::string & fileName) static
Load text data from file (read)
Definition at line 73 of file Functions.hpp.
References LoadFileText().
Referenced by LoadFileText().
LoadFont()
static inline ::Font raylib::LoadFont (const std::string & fileName) static
Load font from file (filename must include file extension)
Definition at line 313 of file Functions.hpp.
Referenced by raylib::Font::Load().
LoadFontEx()
static inline ::Font raylib::LoadFontEx (const std::string & fileName, int fontSize, const int * codepoints = nullptr, int codepointCount = 0) static
Load font from file (filename must include file extension)
Definition at line 321 of file Functions.hpp.
Referenced by raylib::Font::Load().
LoadImage()
static inline ::Image raylib::LoadImage (const std::string & fileName) static
Load an image.
Definition at line 208 of file Functions.hpp.
Referenced by raylib::Image::Load().
LoadImageAnim()
static inline ::Image raylib::LoadImageAnim (const std::string & fileName, int * frames) static
Load animated image data.
Definition at line 223 of file Functions.hpp.
Referenced by raylib::Image::Load().
LoadImageFromMemory()
static inline ::Image raylib::LoadImageFromMemory (const std::string & fileType, const unsigned char * fileData, int dataSize) static
Load image from memory buffer, fileType refers to extension like "png".
Definition at line 231 of file Functions.hpp.
Referenced by raylib::Image::Load().
LoadImageRaw()
static inline ::Image raylib::LoadImageRaw (const std::string & fileName, int width, int height, int format, int headerSize) static
Load an image from RAW file data.
Definition at line 216 of file Functions.hpp.
Referenced by raylib::Image::Load().
MeasureText() [1/2]
static int raylib::MeasureText (const char * text, int fontSize) inline static
Measure string width for default font.
Definition at line 328 of file Functions.hpp.
MeasureText() [2/2]
static int raylib::MeasureText (const std::string & text, int fontSize) inline static
Measure string width for default font.
Definition at line 335 of file Functions.hpp.
OpenURL()
static void raylib::OpenURL (const std::string & url) inline static
Open URL with default system browser (if available)
Definition at line 201 of file Functions.hpp.
SaveFileText()
static bool raylib::SaveFileText (const std::string & fileName, const std::string & text) inline static
Save text data to file (write)
Definition at line 83 of file Functions.hpp.
SetClipboardText()
static void raylib::SetClipboardText (const std::string & text) inline static
Set clipboard text content.
Definition at line 45 of file Functions.hpp.
References SetClipboardText().
Referenced by SetClipboardText().
SetWindowTitle()
static void raylib::SetWindowTitle (const std::string & title) inline static
Set title for window.
Definition at line 31 of file Functions.hpp.
References SetWindowTitle().
Referenced by raylib::Window::SetTitle(), and SetWindowTitle().
TakeScreenshot()
static void raylib::TakeScreenshot (const std::string & fileName) inline static
Takes a screenshot of current screen (saved a .png)
Definition at line 59 of file Functions.hpp.
References TakeScreenshot().
Referenced by TakeScreenshot().
TextFindIndex()
static int raylib::TextFindIndex (const std::string & text, const std::string & find) inline static
Find first text occurrence within a string.
Definition at line 409 of file Functions.hpp.
TextInsert()
static std::string raylib::TextInsert (const std::string & text, const std::string & insert, int position) static
Insert text in a position.
Definition at line 389 of file Functions.hpp.
References TextInsert().
Referenced by TextInsert().
TextIsEqual() [1/2]
static bool raylib::TextIsEqual (const char * text1, const char * text2) inline static
Check if two text string are equal.
Definition at line 342 of file Functions.hpp.
TextIsEqual() [2/2]
static bool raylib::TextIsEqual (const std::string & text1, const std::string & text2) inline static
Check if two text string are equal.
Definition at line 349 of file Functions.hpp.
TextLength() [1/2]
static unsigned int raylib::TextLength (const char * text) inline static
Get text length, checks for '\0' ending.
Definition at line 356 of file Functions.hpp.
TextLength() [2/2]
static unsigned int raylib::TextLength (const std::string & text) inline static
Get text length, checks for '\0' ending.
Definition at line 363 of file Functions.hpp.
TextReplace()
static std::string raylib::TextReplace (const std::string & text, const std::string & replace, const std::string & by) static
Replace text string.
Definition at line 378 of file Functions.hpp.
References TextReplace().
Referenced by TextReplace().
TextSplit()
static std::vector< std::string > raylib::TextSplit (const std::string & text, char delimiter) static
Split text into multiple strings.
Definition at line 400 of file Functions.hpp.
References TextSplit().
Referenced by TextSplit().
TextSubtext()
static std::string raylib::TextSubtext (const std::string & text, int position, int length) inline static
Get a piece of a text string.
Definition at line 370 of file Functions.hpp.
TextToCamel()
static std::string raylib::TextToCamel (const std::string & text) inline static
Get Camel case notation version of provided string.
Definition at line 444 of file Functions.hpp.
TextToFloat()
static float raylib::TextToFloat (const std::string & text) inline static
Get float value from text.
Definition at line 458 of file Functions.hpp.
TextToInteger()
static int raylib::TextToInteger (const std::string & text) inline static
Get integer value from text (negative values not supported)
Definition at line 451 of file Functions.hpp.
TextToLower()
static std::string raylib::TextToLower (const std::string & text) inline static
Get lower case version of provided string.
Definition at line 423 of file Functions.hpp.
TextToPascal()
static std::string raylib::TextToPascal (const std::string & text) inline static
Get Pascal case notation version of provided string.
Definition at line 430 of file Functions.hpp.
TextToSnake()
static std::string raylib::TextToSnake (const std::string & text) inline static
Get Snake case notation version of provided string.
Definition at line 437 of file Functions.hpp.
TextToUpper()
static std::string raylib::TextToUpper (const std::string & text) inline static
Get upper case version of provided string.
Definition at line 416 of file Functions.hpp.