raylib-cpp: raylib::DroppedFiles Class Reference
raylib::DroppedFiles Class Reference
Public Member Functions
DroppedFiles ()
~DroppedFiles ()
std::string at (int pos)
std::string back ()
DroppedFiles & Clear ()
void clear ()
int Count ()
bool empty ()
std::string front ()
DroppedFiles & Get ()
bool IsFileDropped ()
std::string operator[] (int pos)
int size ()
Protected Attributes
int m_count
char ** m_files
Detailed Description
Definition at line 15 of file DroppedFiles.hpp.
Constructor & Destructor Documentation
DroppedFiles()
raylib::DroppedFiles::DroppedFiles () inline
Definition at line 20 of file DroppedFiles.hpp.
References Get().
{
             Get();
         }
~DroppedFiles()
raylib::DroppedFiles::~DroppedFiles () inline
Definition at line 47 of file DroppedFiles.hpp.
References Clear().
{
             Clear();
         }
Member Function Documentation
at()
std::string raylib::DroppedFiles::at (int pos) inline
Definition at line 79 of file DroppedFiles.hpp.
Referenced by back(), front(), and operator[]().
{
             if (m_files != NULL && pos < m_count && pos >= 0) {
                 return std::string(m_files[pos]);
             }
             return "";
         }
back()
std::string raylib::DroppedFiles::back () inline
Definition at line 75 of file DroppedFiles.hpp.
References at().
{
             return at(m_count - 1);
         }
Clear()
DroppedFiles& raylib::DroppedFiles::Clear () inline
Clear dropped files paths buffer.
Definition at line 42 of file DroppedFiles.hpp.
Referenced by clear(), and ~DroppedFiles().
{
             ::ClearDroppedFiles();
             return *this;
         }
clear()
void raylib::DroppedFiles::clear () inline
Definition at line 67 of file DroppedFiles.hpp.
References Clear().
{
             Clear();
         }
Count()
int raylib::DroppedFiles::Count () inline
Definition at line 55 of file DroppedFiles.hpp.
References m_count.
{
             return m_count;
         }
empty()
bool raylib::DroppedFiles::empty () inline
Definition at line 63 of file DroppedFiles.hpp.
{
             return m_count == 0;
         }
front()
std::string raylib::DroppedFiles::front () inline
Definition at line 71 of file DroppedFiles.hpp.
References at().
{
             return at(0);
         }
Get()
DroppedFiles& raylib::DroppedFiles::Get () inline
Get the dropped files names.
Definition at line 27 of file DroppedFiles.hpp.
Referenced by DroppedFiles().
{
             m_files = ::GetDroppedFiles(&m_count);
             return *this;
         }
IsFileDropped()
bool raylib::DroppedFiles::IsFileDropped () inline
Check if a file has been dropped into window.
Definition at line 35 of file DroppedFiles.hpp.
{
             return ::IsFileDropped();
         }
operator[]()
std::string raylib::DroppedFiles::operator[] (int pos) inline
Definition at line 51 of file DroppedFiles.hpp.
References at().
{
             return at(pos);
         }
size()
int raylib::DroppedFiles::size () inline
Definition at line 59 of file DroppedFiles.hpp.
References m_count.
{
             return m_count;
         }
Member Data Documentation
m_count
int raylib::DroppedFiles::m_count protected
Definition at line 18 of file DroppedFiles.hpp.
Referenced by Count(), and size().
m_files
char** raylib::DroppedFiles::m_files protected
Definition at line 17 of file DroppedFiles.hpp.