raylib-cpp: raylib::RenderTexture2D Class Reference
raylib::RenderTexture2D Class Reference
Public Member Functions
RenderTexture2D (::RenderTexture2D renderTexture)
RenderTexture2D (int width, int height)
RenderTexture2D (unsigned int Id)
~RenderTexture2D ()
RenderTexture2D & BeginTextureMode ()
RenderTexture2D & EndTextureMode ()
Texture2D GetDepth ()
unsigned int GetId ()
Texture2D GetTexture ()
RenderTexture2D & operator= (const ::RenderTexture2D &texture)
RenderTexture2D & operator= (const RenderTexture2D &texture)
void set (::RenderTexture2D renderTexture)
void SetDepth (Texture2D value)
void SetId (unsigned int value)
void SetTexture (Texture2D value)
void Unload ()
Detailed Description
Definition at line 15 of file RenderTexture2D.hpp.
Constructor & Destructor Documentation
RenderTexture2D() [1/3]
raylib::RenderTexture2D::RenderTexture2D (::RenderTexture2D renderTexture) inline
Definition at line 17 of file RenderTexture2D.hpp.
References set().
RenderTexture2D() [2/3]
raylib::RenderTexture2D::RenderTexture2D (unsigned int Id) inline
Definition at line 20 of file RenderTexture2D.hpp.
RenderTexture2D() [3/3]
raylib::RenderTexture2D::RenderTexture2D (int width, int height) inline
Definition at line 23 of file RenderTexture2D.hpp.
References set().
~RenderTexture2D()
raylib::RenderTexture2D::~RenderTexture2D () inline
Definition at line 47 of file RenderTexture2D.hpp.
References Unload().
Member Function Documentation
BeginTextureMode()
RenderTexture2D& raylib::RenderTexture2D::BeginTextureMode () inline
Definition at line 55 of file RenderTexture2D.hpp.
EndTextureMode()
RenderTexture2D& raylib::RenderTexture2D::EndTextureMode () inline
Definition at line 60 of file RenderTexture2D.hpp.
GetDepth()
Texture2D raylib::RenderTexture2D::GetDepth () inline
Definition at line 35 of file RenderTexture2D.hpp.
GetId()
unsigned int raylib::RenderTexture2D::GetId () inline
Definition at line 33 of file RenderTexture2D.hpp.
GetTexture()
Texture2D raylib::RenderTexture2D::GetTexture () inline
Definition at line 34 of file RenderTexture2D.hpp.
operator=() [1/2]
RenderTexture2D& raylib::RenderTexture2D::operator= (const ::RenderTexture2D & texture) inline
Definition at line 37 of file RenderTexture2D.hpp.
References set().
operator=() [2/2]
RenderTexture2D& raylib::RenderTexture2D::operator= (const RenderTexture2D & texture) inline
Definition at line 42 of file RenderTexture2D.hpp.
References set().
set()
void raylib::RenderTexture2D::set (::RenderTexture2D renderTexture) inline
Definition at line 27 of file RenderTexture2D.hpp.
Referenced by operator=(), and RenderTexture2D().
SetDepth()
void raylib::RenderTexture2D::SetDepth (Texture2D value) inline
Definition at line 35 of file RenderTexture2D.hpp.
SetId()
void raylib::RenderTexture2D::SetId (unsigned int value) inline
Definition at line 33 of file RenderTexture2D.hpp.
SetTexture()
void raylib::RenderTexture2D::SetTexture (Texture2D value) inline
Definition at line 34 of file RenderTexture2D.hpp.
Unload()
void raylib::RenderTexture2D::Unload () inline
Definition at line 51 of file RenderTexture2D.hpp.
Referenced by ~RenderTexture2D().