raylib-cpp: raylib::TextureUnmanaged Class Reference
raylib::TextureUnmanaged Class Reference
A Texture that is not managed by the C++ garbage collector.
Public Member Functions
TextureUnmanaged ()
Default texture constructor.
TextureUnmanaged (::Texture &&other)
TextureUnmanaged (const ::Image &image)
Creates a texture from the given Image.
TextureUnmanaged (const ::Image &image, int layout)
Load cubemap from image, multiple image cubemap layouts supported.
TextureUnmanaged (const ::Texture &texture)
Creates a texture object based on the given Texture struct data.
TextureUnmanaged (const std::string &fileName)
Load texture from file into GPU memory (VRAM)
TextureUnmanaged (unsigned int id, int width, int height, int mipmaps=1, int format=PIXELFORMAT_UNCOMPRESSED_R8G8B8A8)
Move/Create a texture structure manually.
void Draw (::NPatchInfo nPatchInfo, ::Rectangle destRec, ::Vector2 origin={0, 0}, float rotation=0, ::Color tint={255, 255, 255, 255}) const
Draws a texture (or part of it) that stretches or shrinks nicely.
void Draw (::Rectangle sourceRec, ::Rectangle destRec, ::Vector2 origin={0, 0}, float rotation=0, ::Color tint={255, 255, 255, 255}) const
Draw a part of a texture defined by a rectangle with 'pro' parameters.
void Draw (::Rectangle sourceRec, ::Vector2 position={0, 0}, ::Color tint={255, 255, 255, 255}) const
Draw a part of a texture defined by a rectangle.
void Draw (::Vector2 position, ::Color tint={255, 255, 255, 255}) const
Draw a Texture2D with position defined as Vector2.
void Draw (::Vector2 position, float rotation, float scale=1.0f, ::Color tint={255, 255, 255, 255}) const
Draw a Texture2D with extended parameters.
void Draw (::Vector2 tiling, ::Vector2 offset, ::Rectangle quad, ::Color tint={255, 255, 255, 255}) const
Draw texture quad with tiling and offset parameters.
void Draw (int posX=0, int posY=0, ::Color tint={255, 255, 255, 255}) const
Draw a Texture2D.
void DrawBillboard (const ::Camera &camera, ::Rectangle source, ::Vector3 position, ::Vector2 size, ::Color tint={255, 255, 255, 255}) const
Draw a billboard texture defined by source.
void DrawBillboard (const ::Camera &camera, ::Rectangle source, Vector3 position, ::Vector3 up, Vector2 size, Vector2 origin, float rotation=0.0f, ::Color tint={255, 255, 255, 255}) const
Draw a billboard texture defined by source and rotation.
void DrawBillboard (const ::Camera &camera, ::Vector3 position, float size, ::Color tint={255, 255, 255, 255}) const
Draw a billboard texture.
void DrawCube (::Rectangle source, ::Vector3 position, ::Vector3 dimensions, ::Color color={255, 255, 255, 255}) const
Draw cube with a region of a texture, with dimensions.
void DrawCube (::Rectangle source, ::Vector3 position, float width, float height, float length, ::Color color={255, 255, 255, 255}) const
Draw cube with a region of a texture.
void DrawCube (::Vector3 position, ::Vector3 dimensions, ::Color color={255, 255, 255, 255}) const
Draw cube textured, with dimensions.
void DrawCube (::Vector3 position, float width, float height, float length, ::Color color={255, 255, 255, 255}) const
Draw cube textured.
void DrawPoly (::Vector2 center, ::Vector2 *points, ::Vector2 *texcoords, int pointsCount, ::Color tint={255, 255, 255, 255}) const
Draw a textured polygon.
void DrawTiled (::Rectangle sourceRec, ::Rectangle destRec, ::Vector2 origin={0, 0}, float rotation=0, float scale=1, Color tint={255, 255, 255, 255}) const
Draw part of a texture (defined by a rectangle) with rotation and scale tiled into dest.
TextureUnmanaged & GenMipmaps ()
Generate GPU mipmaps for a texture.
inline ::Image GetData () const
Get pixel data from GPU texture and return an Image.
int GetFormat () const
Retrieves the format value for the object.
int GetHeight () const
Retrieves the height value for the object.
unsigned int GetId () const
Retrieves the id value for the object.
int GetMipmaps () const
Retrieves the mipmaps value for the object.
inline ::Vector2 GetSize () const
Retrieve the width and height of the texture.
int GetWidth () const
Retrieves the width value for the object.
bool IsReady () const
Determines whether or not the Texture has been loaded and is ready.
void Load (const ::Image &image)
Load texture from image data.
void Load (const ::Image &image, int layoutType)
Load cubemap from image, multiple image cubemap layouts supported.
void Load (const std::string &fileName)
Load texture from file into GPU memory (VRAM)
operator Image ()
Get pixel data from GPU texture and return an Image.
TextureUnmanaged & operator= (const ::Texture &texture)
TextureUnmanaged & SetFilter (int filterMode)
Set texture scaling filter mode.
void SetFormat (int value)
Sets the format value for the object.
void SetHeight (int value)
Sets the height value for the object.
void SetId (unsigned int value)
Sets the id value for the object.
TextureUnmanaged & SetMaterial (::Material *material, int mapType=MATERIAL_MAP_NORMAL)
Set texture for a material map type (MAP_DIFFUSE, MAP_SPECULAR...)
TextureUnmanaged & SetMaterial (const ::Material &material, int mapType=MATERIAL_MAP_NORMAL)
void SetMipmaps (int value)
Sets the mipmaps value for the object.
TextureUnmanaged & SetShaderValue (const ::Shader &shader, int locIndex)
Set shader uniform value for texture (sampler2d)
TextureUnmanaged & SetShapes (const ::Rectangle &source)
Set texture and rectangle to be used on shapes drawing.
void SetWidth (int value)
Sets the width value for the object.
TextureUnmanaged & SetWrap (int wrapMode)
Set texture wrapping mode.
void Unload ()
Unload texture from GPU memory (VRAM)
TextureUnmanaged & Update (::Rectangle rec, const void *pixels)
Update GPU texture rectangle with new data.
TextureUnmanaged & Update (const void *pixels)
Update GPU texture with new data.
Protected Member Functions
void set (const ::Texture &texture)
Detailed Description
A Texture that is not managed by the C++ garbage collector.
Make sure to Unload() this if needed, otherwise use raylib::Texture.
See also
raylib::Texture
Definition at line 21 of file TextureUnmanaged.hpp.
Constructor & Destructor Documentation
TextureUnmanaged() [1/3]
raylib::TextureUnmanaged::TextureUnmanaged (const ::Image & image) inline
Creates a texture from the given Image.
Exceptions
raylib::RaylibException Throws if failed to create the texture from the given image.
Definition at line 54 of file TextureUnmanaged.hpp.
References Load().
TextureUnmanaged() [2/3]
raylib::TextureUnmanaged::TextureUnmanaged (const ::Image & image, int layout) inline
Load cubemap from image, multiple image cubemap layouts supported.
Exceptions
raylib::RaylibException Throws if failed to create the texture from the given cubemap.
See also
LoadTextureCubemap()
Definition at line 65 of file TextureUnmanaged.hpp.
References Load().
TextureUnmanaged() [3/3]
raylib::TextureUnmanaged::TextureUnmanaged (const std::string & fileName) inline
Load texture from file into GPU memory (VRAM)
Exceptions
raylib::RaylibException Throws if failed to create the texture from the given file.
Definition at line 74 of file TextureUnmanaged.hpp.
References Load().
Member Function Documentation
Draw() [1/7]
void raylib::TextureUnmanaged::Draw (::NPatchInfo nPatchInfo, ::Rectangle destRec, ::Vector2 origin = {0, 0}, float rotation = 0, ::Color tint = {255, 255, 255, 255}) const inline
Draws a texture (or part of it) that stretches or shrinks nicely.
See also
::DrawTextureNPatch()
Definition at line 259 of file TextureUnmanaged.hpp.
Draw() [2/7]
void raylib::TextureUnmanaged::Draw (::Rectangle sourceRec, ::Rectangle destRec, ::Vector2 origin = {0, 0}, float rotation = 0, ::Color tint = {255, 255, 255, 255}) const inline
Draw a part of a texture defined by a rectangle with 'pro' parameters.
See also
::DrawTexturePro()
Definition at line 249 of file TextureUnmanaged.hpp.
Draw() [3/7]
void raylib::TextureUnmanaged::Draw (::Rectangle sourceRec, ::Vector2 position = {0, 0}, ::Color tint = {255, 255, 255, 255}) const inline
Draw a part of a texture defined by a rectangle.
See also
::DrawTextureRec()
Definition at line 229 of file TextureUnmanaged.hpp.
Draw() [4/7]
void raylib::TextureUnmanaged::Draw (::Vector2 position, ::Color tint = {255, 255, 255, 255}) const inline
Draw a Texture2D with position defined as Vector2.
See also
::DrawTextureV()
Definition at line 210 of file TextureUnmanaged.hpp.
Draw() [5/7]
void raylib::TextureUnmanaged::Draw (::Vector2 position, float rotation, float scale = 1.0f, ::Color tint = {255, 255, 255, 255}) const inline
Draw a Texture2D with extended parameters.
See also
::DrawTextureEx()
Definition at line 219 of file TextureUnmanaged.hpp.
Draw() [6/7]
void raylib::TextureUnmanaged::Draw (::Vector2 tiling, ::Vector2 offset, ::Rectangle quad, ::Color tint = {255, 255, 255, 255}) const inline
Draw texture quad with tiling and offset parameters.
See also
::DrawTextureQuad()
Definition at line 239 of file TextureUnmanaged.hpp.
Draw() [7/7]
void raylib::TextureUnmanaged::Draw (int posX = 0, int posY = 0, ::Color tint = {255, 255, 255, 255}) const inline
Draw a Texture2D.
See also
::DrawTexture()
Definition at line 201 of file TextureUnmanaged.hpp.
DrawBillboard() [1/3]
void raylib::TextureUnmanaged::DrawBillboard (const ::Camera & camera, ::Rectangle source, ::Vector3 position, ::Vector2 size, ::Color tint = {255, 255, 255, 255}) const inline
Draw a billboard texture defined by source.
See also
::DrawBillboardRec()
Definition at line 301 of file TextureUnmanaged.hpp.
DrawBillboard() [2/3]
void raylib::TextureUnmanaged::DrawBillboard (const ::Camera & camera, ::Rectangle source, Vector3 position, ::Vector3 up, Vector2 size, Vector2 origin, float rotation = 0.0f, ::Color tint = {255, 255, 255, 255}) const inline
Draw a billboard texture defined by source and rotation.
See also
::DrawBillboardPro()
Definition at line 312 of file TextureUnmanaged.hpp.
DrawBillboard() [3/3]
void raylib::TextureUnmanaged::DrawBillboard (const ::Camera & camera, ::Vector3 position, float size, ::Color tint = {255, 255, 255, 255}) const inline
Draw a billboard texture.
See also
::DrawBillboard()
Definition at line 290 of file TextureUnmanaged.hpp.
DrawCube() [1/4]
void raylib::TextureUnmanaged::DrawCube (::Rectangle source, ::Vector3 position, ::Vector3 dimensions, ::Color color = {255, 255, 255, 255}) const inline
Draw cube with a region of a texture, with dimensions.
See also
::DrawCubeTextureRec()
Definition at line 354 of file TextureUnmanaged.hpp.
DrawCube() [2/4]
void raylib::TextureUnmanaged::DrawCube (::Rectangle source, ::Vector3 position, float width, float height, float length, ::Color color = {255, 255, 255, 255}) const inline
Draw cube with a region of a texture.
See also
::DrawCubeTextureRec()
Definition at line 344 of file TextureUnmanaged.hpp.
DrawCube() [3/4]
void raylib::TextureUnmanaged::DrawCube (::Vector3 position, ::Vector3 dimensions, ::Color color = {255, 255, 255, 255}) const inline
Draw cube textured, with dimensions.
See also
::DrawCubeTexture()
Definition at line 334 of file TextureUnmanaged.hpp.
DrawCube() [4/4]
void raylib::TextureUnmanaged::DrawCube (::Vector3 position, float width, float height, float length, ::Color color = {255, 255, 255, 255}) const inline
Draw cube textured.
See also
::DrawCubeTexture()
Definition at line 324 of file TextureUnmanaged.hpp.
DrawPoly()
void raylib::TextureUnmanaged::DrawPoly (::Vector2 center, ::Vector2 * points, ::Vector2 * texcoords, int pointsCount, ::Color tint = {255, 255, 255, 255}) const inline
Draw a textured polygon.
See also
::DrawTexturePoly()
Definition at line 279 of file TextureUnmanaged.hpp.
DrawTiled()
void raylib::TextureUnmanaged::DrawTiled (::Rectangle sourceRec, ::Rectangle destRec, ::Vector2 origin = {0, 0}, float rotation = 0, float scale = 1, Color tint = {255, 255, 255, 255}) const inline
Draw part of a texture (defined by a rectangle) with rotation and scale tiled into dest.
See also
::DrawTextureTiled()
Definition at line 269 of file TextureUnmanaged.hpp.
GetFormat()
int raylib::TextureUnmanaged::GetFormat () const inline
Retrieves the format value for the object.
Returns
The format value of the object.
Definition at line 87 of file TextureUnmanaged.hpp.
GetHeight()
int raylib::TextureUnmanaged::GetHeight () const inline
Retrieves the height value for the object.
Returns
The height value of the object.
Definition at line 85 of file TextureUnmanaged.hpp.
GetId()
unsigned int raylib::TextureUnmanaged::GetId () const inline
Retrieves the id value for the object.
Returns
The id value of the object.
Definition at line 83 of file TextureUnmanaged.hpp.
GetMipmaps()
int raylib::TextureUnmanaged::GetMipmaps () const inline
Retrieves the mipmaps value for the object.
Returns
The mipmaps value of the object.
Definition at line 86 of file TextureUnmanaged.hpp.
GetWidth()
int raylib::TextureUnmanaged::GetWidth () const inline
Retrieves the width value for the object.
Returns
The width value of the object.
Definition at line 84 of file TextureUnmanaged.hpp.
IsReady()
bool raylib::TextureUnmanaged::IsReady () const inline
Determines whether or not the Texture has been loaded and is ready.
Returns
True or false depending on whether the Texture has data.
Definition at line 393 of file TextureUnmanaged.hpp.
Referenced by Load().
SetFormat()
void raylib::TextureUnmanaged::SetFormat (int value) inline
Sets the format value for the object.
Parameters
value The value of which to set format to.
Definition at line 87 of file TextureUnmanaged.hpp.
SetHeight()
void raylib::TextureUnmanaged::SetHeight (int value) inline
Sets the height value for the object.
Parameters
value The value of which to set height to.
Definition at line 85 of file TextureUnmanaged.hpp.
SetId()
void raylib::TextureUnmanaged::SetId (unsigned int value) inline
Sets the id value for the object.
Parameters
value The value of which to set id to.
Definition at line 83 of file TextureUnmanaged.hpp.
SetMipmaps()
void raylib::TextureUnmanaged::SetMipmaps (int value) inline
Sets the mipmaps value for the object.
Parameters
value The value of which to set mipmaps to.
Definition at line 86 of file TextureUnmanaged.hpp.
SetWidth()
void raylib::TextureUnmanaged::SetWidth (int value) inline
Sets the width value for the object.
Parameters
value The value of which to set width to.
Definition at line 84 of file TextureUnmanaged.hpp.