raylib-cpp: raylib::Vector3 Class Reference
raylib::Vector3 Class Reference
Vector3 type.
#include <Vector3.hpp>
Public Member Functions
Vector3 ()
Vector3 (::Color color)
Vector3 (const ::Vector3 &vec)
Vector3 (float x)
Vector3 (float x, float y)
Vector3 (float x, float y, float z)
Vector3 Add (const ::Vector3 &vector3)
Vector3 Barycenter (const ::Vector3 &a, const ::Vector3 &b, const ::Vector3 &c)
bool CheckCollision (float radius1, const ::Vector3 &center2, float radius2)
Detect collision between two spheres.
Vector3 CrossProduct (const ::Vector3 &vector3) const
float Distance (const ::Vector3 &vector3) const
Vector3 Divide (const ::Vector3 &vector3) const
Vector3 Divide (const float div) const
float DotProduct (const ::Vector3 &vector3)
Vector3 & DrawCircle3D (float radius, const ::Vector3 &rotationAxis, float rotationAngle, Color color)
Vector3 & DrawCube (const ::Vector3 &size, ::Color color)
Vector3 & DrawCube (float width, float height, float length, ::Color color)
Vector3 & DrawCubeTexture (const ::Texture2D &texture, float width, float height, float length, ::Color color)
Vector3 & DrawCubeWires (const ::Vector3 &size, ::Color color)
Vector3 & DrawCubeWires (float width, float height, float length, ::Color color)
Vector3 & DrawCylinder (float radiusTop, float radiusBottom, float height, int slices, Color color)
Vector3 & DrawCylinderWires (float radiusTop, float radiusBottom, float height, int slices, Color color)
Vector3 & DrawLine3D (const ::Vector3 &endPos, ::Color color)
Vector3 & DrawPlane (const ::Vector2 &size, ::Color color)
Vector3 & DrawPoint3D (::Color color)
Vector3 & DrawSphere (float radius, ::Color color)
Vector3 & DrawSphere (float radius, int rings, int slices, ::Color color)
Vector3 & DrawSphereWires (float radius, int rings, int slices, ::Color color)
float GetX () const
Retrieves the x value for the object.
float GetY () const
Retrieves the y value for the object.
float GetZ () const
Retrieves the z value for the object.
float Length () const
Vector3 Lerp (const ::Vector3 &vector3, const float amount) const
Vector3 Max (const ::Vector3 &vector3)
Vector3 Min (const ::Vector3 &vector3)
Vector3 Multiply (const ::Vector3 &vector3) const
Vector3 Negate ()
Vector3 Normalize () const
bool operator!= (const ::Vector3 &other)
Vector3 operator* (const ::Vector3 &vector3) const
Vector3 operator* (const float scale) const
Vector3 & operator*= (const ::Vector3 &vector3)
Vector3 & operator*= (const float scale)
Vector3 operator+ (const ::Vector3 &vector3)
Vector3 & operator+= (const ::Vector3 &vector3)
Vector3 operator- ()
Vector3 operator- (const ::Vector3 &vector3)
Vector3 & operator-= (const ::Vector3 &vector3)
Vector3 operator/ (const ::Vector3 &vector3) const
Vector3 operator/ (const float div) const
Vector3 & operator/= (const ::Vector3 &vector3)
Vector3 & operator/= (const float div)
Vector3 & operator= (const ::Vector3 &vector3)
bool operator== (const ::Vector3 &other)
void OrthoNormalize (::Vector3 *vector3)
Vector3 Perpendicular () const
Vector3 Reflect (const ::Vector3 &normal) const
Vector3 RotateByQuaternion (const ::Quaternion &quaternion)
Vector3 Scale (const float scale) const
void SetX (float value)
Sets the x value for the object.
void SetY (float value)
Sets the y value for the object.
void SetZ (float value)
Sets the z value for the object.
Vector3 Subtract (const ::Vector3 &vector3)
Vector3 Transform (const ::Matrix &matrix) const
Static Public Member Functions
static Vector3 One ()
static Vector3 Zero ()
Detailed Description
Vector3 type.
Definition at line 16 of file Vector3.hpp.
Constructor & Destructor Documentation
Vector3() [1/6]
raylib::Vector3::Vector3 (const ::Vector3 & vec) inline
Definition at line 18 of file Vector3.hpp.
Vector3() [2/6]
raylib::Vector3::Vector3 (float x, float y, float z) inline
Definition at line 22 of file Vector3.hpp.
Vector3() [3/6]
raylib::Vector3::Vector3 (float x, float y) inline
Definition at line 23 of file Vector3.hpp.
Vector3() [4/6]
raylib::Vector3::Vector3 (float x) inline
Definition at line 24 of file Vector3.hpp.
Vector3() [5/6]
raylib::Vector3::Vector3 () inline
Definition at line 25 of file Vector3.hpp.
Vector3() [6/6]
raylib::Vector3::Vector3 (::Color color) inline
Definition at line 27 of file Vector3.hpp.
Member Function Documentation
Add()
Vector3 raylib::Vector3::Add (const ::Vector3 & vector3) inline
Definition at line 51 of file Vector3.hpp.
Barycenter()
Vector3 raylib::Vector3::Barycenter (const ::Vector3 & a, const ::Vector3 & b, const ::Vector3 & c) inline
Definition at line 200 of file Vector3.hpp.
CheckCollision()
bool raylib::Vector3::CheckCollision (float radius1, const ::Vector3 & center2, float radius2) inline
Detect collision between two spheres.
Definition at line 297 of file Vector3.hpp.
CrossProduct()
Vector3 raylib::Vector3::CrossProduct (const ::Vector3 & vector3) const inline
Definition at line 168 of file Vector3.hpp.
Distance()
float raylib::Vector3::Distance (const ::Vector3 & vector3) const inline
Definition at line 160 of file Vector3.hpp.
Divide() [1/2]
Vector3 raylib::Vector3::Divide (const ::Vector3 & vector3) const inline
Definition at line 91 of file Vector3.hpp.
Referenced by operator/().
Divide() [2/2]
Vector3 raylib::Vector3::Divide (const float div) const inline
Definition at line 99 of file Vector3.hpp.
DotProduct()
float raylib::Vector3::DotProduct (const ::Vector3 & vector3) inline
Definition at line 156 of file Vector3.hpp.
DrawCircle3D()
Vector3 & raylib::Vector3::DrawCircle3D (float radius, const ::Vector3 & rotationAxis, float rotationAngle, Color color) inline
Definition at line 223 of file Vector3.hpp.
References DrawCircle3D().
Referenced by DrawCircle3D().
DrawCube() [1/2]
Vector3 & raylib::Vector3::DrawCube (const ::Vector3 & size, ::Color color) inline
Definition at line 237 of file Vector3.hpp.
DrawCube() [2/2]
Vector3 & raylib::Vector3::DrawCube (float width, float height, float length, ::Color color) inline
Definition at line 232 of file Vector3.hpp.
References DrawCube().
Referenced by DrawCube().
DrawCubeTexture()
Vector3 & raylib::Vector3::DrawCubeTexture (const ::Texture2D & texture, float width, float height, float length, ::Color color) inline
Definition at line 252 of file Vector3.hpp.
References DrawCubeTexture().
Referenced by DrawCubeTexture().
DrawCubeWires() [1/2]
Vector3 & raylib::Vector3::DrawCubeWires (const ::Vector3 & size, ::Color color) inline
Definition at line 247 of file Vector3.hpp.
DrawCubeWires() [2/2]
Vector3 & raylib::Vector3::DrawCubeWires (float width, float height, float length, ::Color color) inline
Definition at line 242 of file Vector3.hpp.
References DrawCubeWires().
Referenced by DrawCubeWires().
DrawCylinder()
Vector3 & raylib::Vector3::DrawCylinder (float radiusTop, float radiusBottom, float height, int slices, Color color) inline
Definition at line 277 of file Vector3.hpp.
References DrawCylinder().
Referenced by DrawCylinder().
DrawCylinderWires()
Vector3 & raylib::Vector3::DrawCylinderWires (float radiusTop, float radiusBottom, float height, int slices, Color color) inline
Definition at line 283 of file Vector3.hpp.
References DrawCylinderWires().
Referenced by DrawCylinderWires().
DrawLine3D()
Vector3 & raylib::Vector3::DrawLine3D (const ::Vector3 & endPos, ::Color color) inline
Definition at line 213 of file Vector3.hpp.
References DrawLine3D().
Referenced by DrawLine3D().
DrawPlane()
Vector3 & raylib::Vector3::DrawPlane (const ::Vector2 & size, ::Color color) inline
Definition at line 289 of file Vector3.hpp.
References DrawPlane().
Referenced by DrawPlane().
DrawPoint3D()
Vector3 & raylib::Vector3::DrawPoint3D (::Color color) inline
Definition at line 218 of file Vector3.hpp.
References DrawPoint3D().
Referenced by DrawPoint3D().
DrawSphere() [1/2]
Vector3 & raylib::Vector3::DrawSphere (float radius, ::Color color) inline
Definition at line 262 of file Vector3.hpp.
References DrawSphere().
Referenced by DrawSphere().
DrawSphere() [2/2]
Vector3 & raylib::Vector3::DrawSphere (float radius, int rings, int slices, ::Color color) inline
Definition at line 267 of file Vector3.hpp.
DrawSphereWires()
Vector3 & raylib::Vector3::DrawSphereWires (float radius, int rings, int slices, ::Color color) inline
Definition at line 272 of file Vector3.hpp.
References DrawSphereWires().
Referenced by DrawSphereWires().
GetX()
float raylib::Vector3::GetX () const inline
Retrieves the x value for the object.
Returns
The x value of the object.
Definition at line 31 of file Vector3.hpp.
GetY()
float raylib::Vector3::GetY () const inline
Retrieves the y value for the object.
Returns
The y value of the object.
Definition at line 32 of file Vector3.hpp.
GetZ()
float raylib::Vector3::GetZ () const inline
Retrieves the z value for the object.
Returns
The z value of the object.
Definition at line 33 of file Vector3.hpp.
Length()
float raylib::Vector3::Length () const inline
Definition at line 148 of file Vector3.hpp.
Lerp()
Vector3 raylib::Vector3::Lerp (const ::Vector3 & vector3, const float amount) const inline
Definition at line 164 of file Vector3.hpp.
Max()
Vector3 raylib::Vector3::Max (const ::Vector3 & vector3) inline
Definition at line 196 of file Vector3.hpp.
Min()
Vector3 raylib::Vector3::Min (const ::Vector3 & vector3) inline
Definition at line 192 of file Vector3.hpp.
Multiply()
Vector3 raylib::Vector3::Multiply (const ::Vector3 & vector3) const inline
Definition at line 75 of file Vector3.hpp.
Negate()
Vector3 raylib::Vector3::Negate () inline
Definition at line 67 of file Vector3.hpp.
Normalize()
Vector3 raylib::Vector3::Normalize () const inline
Definition at line 152 of file Vector3.hpp.
One()
static Vector3 raylib::Vector3::One () inline static
Definition at line 208 of file Vector3.hpp.
operator!=()
bool raylib::Vector3::operator!= (const ::Vector3 & other) inline
Definition at line 46 of file Vector3.hpp.
operator*() [1/2]
Vector3 raylib::Vector3::operator* (const ::Vector3 & vector3) const inline
Definition at line 79 of file Vector3.hpp.
operator*() [2/2]
Vector3 raylib::Vector3::operator* (const float scale) const inline
Definition at line 87 of file Vector3.hpp.
operator*=() [1/2]
Vector3 & raylib::Vector3::operator*= (const ::Vector3 & vector3) inline
Definition at line 120 of file Vector3.hpp.
operator*=() [2/2]
Vector3 & raylib::Vector3::operator*= (const float scale) inline
Definition at line 126 of file Vector3.hpp.
operator+()
Vector3 raylib::Vector3::operator+ (const ::Vector3 & vector3) inline
Definition at line 55 of file Vector3.hpp.
operator+=()
Vector3 & raylib::Vector3::operator+= (const ::Vector3 & vector3) inline
Definition at line 107 of file Vector3.hpp.
operator-() [1/2]
Vector3 raylib::Vector3::operator- () inline
Definition at line 71 of file Vector3.hpp.
operator-() [2/2]
Vector3 raylib::Vector3::operator- (const ::Vector3 & vector3) inline
Definition at line 63 of file Vector3.hpp.
operator-=()
Vector3 & raylib::Vector3::operator-= (const ::Vector3 & vector3) inline
Definition at line 113 of file Vector3.hpp.
operator/() [1/2]
Vector3 raylib::Vector3::operator/ (const ::Vector3 & vector3) const inline
Definition at line 95 of file Vector3.hpp.
operator/() [2/2]
Vector3 raylib::Vector3::operator/ (const float div) const inline
Definition at line 103 of file Vector3.hpp.
References Divide().
operator/=() [1/2]
Vector3 & raylib::Vector3::operator/= (const ::Vector3 & vector3) inline
Definition at line 132 of file Vector3.hpp.
operator/=() [2/2]
Vector3 & raylib::Vector3::operator/= (const float div) inline
Definition at line 140 of file Vector3.hpp.
operator=()
Vector3 & raylib::Vector3::operator= (const ::Vector3 & vector3) inline
Definition at line 35 of file Vector3.hpp.
operator==()
bool raylib::Vector3::operator== (const ::Vector3 & other) inline
Definition at line 40 of file Vector3.hpp.
OrthoNormalize()
void raylib::Vector3::OrthoNormalize (::Vector3 * vector3) inline
Definition at line 176 of file Vector3.hpp.
Perpendicular()
Vector3 raylib::Vector3::Perpendicular () const inline
Definition at line 172 of file Vector3.hpp.
Reflect()
Vector3 raylib::Vector3::Reflect (const ::Vector3 & normal) const inline
Definition at line 188 of file Vector3.hpp.
RotateByQuaternion()
Vector3 raylib::Vector3::RotateByQuaternion (const ::Quaternion & quaternion) inline
Definition at line 184 of file Vector3.hpp.
Scale()
Vector3 raylib::Vector3::Scale (const float scale) const inline
Definition at line 83 of file Vector3.hpp.
SetX()
void raylib::Vector3::SetX (float value) inline
Sets the x value for the object.
Parameters
value The value of which to set x to.
Definition at line 31 of file Vector3.hpp.
SetY()
void raylib::Vector3::SetY (float value) inline
Sets the y value for the object.
Parameters
value The value of which to set y to.
Definition at line 32 of file Vector3.hpp.
SetZ()
void raylib::Vector3::SetZ (float value) inline
Sets the z value for the object.
Parameters
value The value of which to set z to.
Definition at line 33 of file Vector3.hpp.
Subtract()
Vector3 raylib::Vector3::Subtract (const ::Vector3 & vector3) inline
Definition at line 59 of file Vector3.hpp.
Transform()
Vector3 raylib::Vector3::Transform (const ::Matrix & matrix) const inline
Definition at line 180 of file Vector3.hpp.
Zero()
static Vector3 raylib::Vector3::Zero () inline static
Definition at line 204 of file Vector3.hpp.