raylib-cpp: raylib::VrSimulator Class Reference
raylib::VrSimulator Class Reference
Public Member Functions
VrSimulator ()
VrSimulator (::VrDeviceInfo info, ::Shader distortion)
~VrSimulator ()
Close VR simulator for current device.
VrSimulator & BeginDrawing ()
Begin VR simulator stereo rendering.
void Close ()
Close VR simulator for current device.
VrSimulator & EndDrawing ()
End VR simulator stereo rendering.
void Init ()
Init VR simulator for selected device parameters.
bool IsReady () const
Detect if VR simulator is ready.
VrSimulator & Set (::VrDeviceInfo info, ::Shader distortion)
Set stereo rendering configuration parameters.
VrSimulator & Toggle ()
Enable/Disable VR experience.
VrSimulator & Update (::Camera *camera)
Update VR tracking (position and orientation) and camera.
VrSimulator & Update (const ::Camera &camera)
Update VR tracking (position and orientation) and camera.
Detailed Description
Definition at line 32 of file VrSimulator.hpp.
Constructor & Destructor Documentation
VrSimulator() [1/2]
raylib::VrSimulator::VrSimulator () inline
Definition at line 34 of file VrSimulator.hpp.
References Init().
VrSimulator() [2/2]
raylib::VrSimulator::VrSimulator (::VrDeviceInfo info, ::Shader distortion) inline
Definition at line 38 of file VrSimulator.hpp.
References Init(), and Set().
~VrSimulator()
raylib::VrSimulator::~VrSimulator () inline
Close VR simulator for current device.
Definition at line 53 of file VrSimulator.hpp.
References Close().
Member Function Documentation
BeginDrawing()
VrSimulator& raylib::VrSimulator::BeginDrawing () inline
Begin VR simulator stereo rendering.
Definition at line 100 of file VrSimulator.hpp.
Close()
void raylib::VrSimulator::Close () inline
Close VR simulator for current device.
Definition at line 116 of file VrSimulator.hpp.
Referenced by ~VrSimulator().
EndDrawing()
VrSimulator& raylib::VrSimulator::EndDrawing () inline
End VR simulator stereo rendering.
Definition at line 108 of file VrSimulator.hpp.
Init()
void raylib::VrSimulator::Init () inline
Init VR simulator for selected device parameters.
Definition at line 46 of file VrSimulator.hpp.
Referenced by VrSimulator().
IsReady()
bool raylib::VrSimulator::IsReady () const inline
Detect if VR simulator is ready.
Definition at line 60 of file VrSimulator.hpp.
Set()
VrSimulator& raylib::VrSimulator::Set (::VrDeviceInfo info, ::Shader distortion) inline
Set stereo rendering configuration parameters.
Definition at line 84 of file VrSimulator.hpp.
Referenced by VrSimulator().
Toggle()
VrSimulator& raylib::VrSimulator::Toggle () inline
Enable/Disable VR experience.
Definition at line 92 of file VrSimulator.hpp.
Update() [1/2]
VrSimulator& raylib::VrSimulator::Update (::Camera * camera) inline
Update VR tracking (position and orientation) and camera.
Definition at line 67 of file VrSimulator.hpp.
Update() [2/2]
VrSimulator& raylib::VrSimulator::Update (const ::Camera & camera) inline
Update VR tracking (position and orientation) and camera.
Definition at line 75 of file VrSimulator.hpp.