raylib-cpp: raylib::Texture Class Reference
raylib::Texture Class Reference
Texture type.
#include <Texture.hpp>
Public Member Functions
Texture (const ::Image &image)
Creates a texture from the given Image.
Texture (const ::Image &image, int layout)
Load cubemap from image, multiple image cubemap layouts supported.
Texture (const ::Texture &texture)
Creates a texture object based on the given Texture struct data.
Texture (const std::string &fileName)
Load texture from file into GPU memory (VRAM)
Texture (const Texture &)=delete
Texture (Texture &&other)
Texture (unsigned int id=0, int width=0, int height=0, int mipmaps=0, int format=0)
Default constructor to create an empty Texture object.
~Texture ()
Texture & Draw (::NPatchInfo nPatchInfo, ::Rectangle destRec, ::Vector2 origin={0, 0}, float rotation=0, ::Color tint={255, 255, 255, 255})
Texture & Draw (::Rectangle sourceRec, ::Rectangle destRec, ::Vector2 origin={0, 0}, float rotation=0, ::Color tint={255, 255, 255, 255})
Texture & Draw (::Rectangle sourceRec, ::Vector2 position={0, 0}, ::Color tint={255, 255, 255, 255})
Texture & Draw (::Vector2 position, ::Color tint={255, 255, 255, 255})
Texture & Draw (::Vector2 position, float rotation, float scale=1.0f, ::Color tint={255, 255, 255, 255})
Texture & Draw (::Vector2 tiling, ::Vector2 offset, ::Rectangle quad, ::Color tint={255, 255, 255, 255})
Texture & Draw (::Vector3 position, float width, float height, float length, ::Color tint={255, 255, 255, 255})
Texture & Draw (int posX=0, int posY=0, ::Color tint={255, 255, 255, 255})
Draw a Texture2D.
Texture & DrawPoly (Vector2 center, Vector2 *points, Vector2 *texcoords, int pointsCount, Color tint={255, 255, 255, 255})
Texture & DrawTiled (::Rectangle sourceRec, ::Rectangle destRec, ::Vector2 origin={0, 0}, float rotation=0, float scale=1, Color tint={255, 255, 255, 255})
Texture & GenMipmaps ()
Generate GPU mipmaps for a texture.
inline ::Image GetData () const
Get pixel data from GPU texture and return an Image.
int GetFormat () const
Retrieves the format value for the object.
int GetHeight () const
Retrieves the height value for the object.
unsigned int GetId () const
Retrieves the id value for the object.
int GetMipmaps () const
Retrieves the mipmaps value for the object.
inline ::Vector2 GetSize () const
Retrieve the width and height of the texture.
int GetWidth () const
Retrieves the width value for the object.
bool IsReady () const
Determines whether or not the Texture has been loaded and is ready.
bool Load (const ::Image &image)
Load texture from image data.
bool Load (const ::Image &image, int layoutType)
Load cubemap from image, multiple image cubemap layouts supported.
bool Load (const std::string &fileName)
Load texture from file into GPU memory (VRAM)
operator raylib::Image ()
Get pixel data from GPU texture and return an Image.
Texture & operator= (const ::Texture &texture)
Texture & operator= (const Texture &)=delete
Texture & operator= (Texture &&other) noexcept
Texture & SetFilter (int filterMode)
Set texture scaling filter mode.
void SetFormat (int value)
Sets the format value for the object.
void SetHeight (int value)
Sets the height value for the object.
void SetId (unsigned int value)
Sets the id value for the object.
Texture & SetMaterial (::Material *material, int mapType=MATERIAL_MAP_NORMAL)
Set texture for a material map type (MAP_DIFFUSE, MAP_SPECULAR...)
Texture & SetMaterial (const ::Material &material, int mapType=MATERIAL_MAP_NORMAL)
void SetMipmaps (int value)
Sets the mipmaps value for the object.
Texture & SetShaderValue (const ::Shader &shader, int locIndex)
Set shader uniform value for texture (sampler2d)
Texture & SetShapes (const ::Rectangle &source)
Set texture and rectangle to be used on shapes drawing.
void SetWidth (int value)
Sets the width value for the object.
Texture & SetWrap (int wrapMode)
Set texture wrapping mode.
void Unload ()
Unload texture from GPU memory (VRAM)
Texture & Update (::Rectangle rec, const void *pixels)
Update GPU texture rectangle with new data.
Texture & Update (const void *pixels)
Update GPU texture with new data.
Detailed Description
Texture type.
Definition at line 16 of file Texture.hpp.
Constructor & Destructor Documentation
Texture() [1/7]
raylib::Texture::Texture (unsigned int id = 0, int width = 0, int height = 0, int mipmaps = 0, int format = 0) inline
Default constructor to create an empty Texture object.
Definition at line 21 of file Texture.hpp.
Texture() [2/7]
raylib::Texture::Texture (const ::Texture & texture) inline
Creates a texture object based on the given Texture struct data.
Definition at line 32 of file Texture.hpp.
Texture() [3/7]
raylib::Texture::Texture (const ::Image & image) inline
Creates a texture from the given Image.
Exceptions
raylib::RaylibException Throws if failed to create the texture from the given image.
Definition at line 41 of file Texture.hpp.
References Load().
Texture() [4/7]
raylib::Texture::Texture (const ::Image & image, int layout) inline
Load cubemap from image, multiple image cubemap layouts supported.
Exceptions
raylib::RaylibException Throws if failed to create the texture from the given cubemap.
See also
LoadTextureCubemap()
Definition at line 54 of file Texture.hpp.
References Load().
Texture() [5/7]
raylib::Texture::Texture (const std::string & fileName) inline
Load texture from file into GPU memory (VRAM)
Exceptions
raylib::RaylibException Throws if failed to create the texture from the given file.
Definition at line 65 of file Texture.hpp.
References Load().
Texture() [6/7]
raylib::Texture::Texture (const Texture &) delete
Texture() [7/7]
raylib::Texture::Texture (Texture && other) inline
Definition at line 73 of file Texture.hpp.
~Texture()
raylib::Texture::~Texture () inline
Definition at line 83 of file Texture.hpp.
References Unload().
Member Function Documentation
Draw() [1/8]
Texture & raylib::Texture::Draw (::NPatchInfo nPatchInfo, ::Rectangle destRec, ::Vector2 origin = {0, 0}, float rotation = 0, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 246 of file Texture.hpp.
Draw() [2/8]
Texture & raylib::Texture::Draw (::Rectangle sourceRec, ::Rectangle destRec, ::Vector2 origin = {0, 0}, float rotation = 0, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 240 of file Texture.hpp.
Draw() [3/8]
Texture & raylib::Texture::Draw (::Rectangle sourceRec, ::Vector2 position = {0, 0}, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 228 of file Texture.hpp.
Draw() [4/8]
Texture & raylib::Texture::Draw (::Vector2 position, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 217 of file Texture.hpp.
Draw() [5/8]
Texture & raylib::Texture::Draw (::Vector2 position, float rotation, float scale = 1.0f, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 222 of file Texture.hpp.
Draw() [6/8]
Texture & raylib::Texture::Draw (::Vector2 tiling, ::Vector2 offset, ::Rectangle quad, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 234 of file Texture.hpp.
Draw() [7/8]
Texture & raylib::Texture::Draw (::Vector3 position, float width, float height, float length, ::Color tint = {255, 255, 255, 255}) inline
Definition at line 252 of file Texture.hpp.
Draw() [8/8]
Texture & raylib::Texture::Draw (int posX = 0, int posY = 0, ::Color tint = {255, 255, 255, 255}) inline
Draw a Texture2D.
Definition at line 212 of file Texture.hpp.
DrawPoly()
Texture & raylib::Texture::DrawPoly (Vector2 center, Vector2 * points, Vector2 * texcoords, int pointsCount, Color tint = {255, 255, 255, 255}) inline
Definition at line 264 of file Texture.hpp.
DrawTiled()
Texture & raylib::Texture::DrawTiled (::Rectangle sourceRec, ::Rectangle destRec, ::Vector2 origin = {0, 0}, float rotation = 0, float scale = 1, Color tint = {255, 255, 255, 255}) inline
Definition at line 258 of file Texture.hpp.
GenMipmaps()
Texture & raylib::Texture::GenMipmaps () inline
Generate GPU mipmaps for a texture.
Definition at line 188 of file Texture.hpp.
GetData()
inline ::Image raylib::Texture::GetData () const inline
Get pixel data from GPU texture and return an Image.
Definition at line 174 of file Texture.hpp.
Referenced by operator raylib::Image().
GetFormat()
int raylib::Texture::GetFormat () const inline
Retrieves the format value for the object.
Returns
The format value of the object.
Definition at line 91 of file Texture.hpp.
GetHeight()
int raylib::Texture::GetHeight () const inline
Retrieves the height value for the object.
Returns
The height value of the object.
Definition at line 89 of file Texture.hpp.
GetId()
unsigned int raylib::Texture::GetId () const inline
Retrieves the id value for the object.
Returns
The id value of the object.
Definition at line 87 of file Texture.hpp.
GetMipmaps()
int raylib::Texture::GetMipmaps () const inline
Retrieves the mipmaps value for the object.
Returns
The mipmaps value of the object.
Definition at line 90 of file Texture.hpp.
GetSize()
inline ::Vector2 raylib::Texture::GetSize () const inline
Retrieve the width and height of the texture.
Definition at line 120 of file Texture.hpp.
GetWidth()
int raylib::Texture::GetWidth () const inline
Retrieves the width value for the object.
Returns
The width value of the object.
Definition at line 88 of file Texture.hpp.
IsReady()
bool raylib::Texture::IsReady () const inline
Determines whether or not the Texture has been loaded and is ready.
Returns
True or false depending on whether the Texture has data.
Definition at line 305 of file Texture.hpp.
Referenced by Load().
Load() [1/3]
bool raylib::Texture::Load (const ::Image & image) inline
Load texture from image data.
Definition at line 127 of file Texture.hpp.
References IsReady().
Referenced by Texture().
Load() [2/3]
bool raylib::Texture::Load (const ::Image & image, int layoutType) inline
Load cubemap from image, multiple image cubemap layouts supported.
Definition at line 135 of file Texture.hpp.
References IsReady().
Load() [3/3]
bool raylib::Texture::Load (const std::string & fileName) inline
Load texture from file into GPU memory (VRAM)
Definition at line 143 of file Texture.hpp.
References IsReady().
operator raylib::Image()
raylib::Texture::operator raylib::Image () inline
Get pixel data from GPU texture and return an Image.
Definition at line 181 of file Texture.hpp.
References GetData().
operator=() [1/3]
Texture & raylib::Texture::operator= (const ::Texture & texture) inline
Definition at line 93 of file Texture.hpp.
operator=() [2/3]
Texture & raylib::Texture::operator= (const Texture &) delete
operator=() [3/3]
Texture & raylib::Texture::operator= (Texture && other) inline noexcept
Definition at line 100 of file Texture.hpp.
References Unload().
SetFilter()
Texture & raylib::Texture::SetFilter (int filterMode) inline
Set texture scaling filter mode.
Definition at line 196 of file Texture.hpp.
SetFormat()
void raylib::Texture::SetFormat (int value) inline
Sets the format value for the object.
Parameters
value The value of which to set format to.
Definition at line 91 of file Texture.hpp.
SetHeight()
void raylib::Texture::SetHeight (int value) inline
Sets the height value for the object.
Parameters
value The value of which to set height to.
Definition at line 89 of file Texture.hpp.
SetId()
void raylib::Texture::SetId (unsigned int value) inline
Sets the id value for the object.
Parameters
value The value of which to set id to.
Definition at line 87 of file Texture.hpp.
SetMaterial() [1/2]
Texture & raylib::Texture::SetMaterial (::Material * material, int mapType = MATERIAL_MAP_NORMAL) inline
Set texture for a material map type (MAP_DIFFUSE, MAP_SPECULAR...)
Definition at line 274 of file Texture.hpp.
SetMaterial() [2/2]
Texture & raylib::Texture::SetMaterial (const ::Material & material, int mapType = MATERIAL_MAP_NORMAL) inline
Definition at line 279 of file Texture.hpp.
SetMipmaps()
void raylib::Texture::SetMipmaps (int value) inline
Sets the mipmaps value for the object.
Parameters
value The value of which to set mipmaps to.
Definition at line 90 of file Texture.hpp.
SetShaderValue()
Texture & raylib::Texture::SetShaderValue (const ::Shader & shader, int locIndex) inline
Set shader uniform value for texture (sampler2d)
Definition at line 295 of file Texture.hpp.
SetShapes()
Texture & raylib::Texture::SetShapes (const ::Rectangle & source) inline
Set texture and rectangle to be used on shapes drawing.
Definition at line 287 of file Texture.hpp.
SetWidth()
void raylib::Texture::SetWidth (int value) inline
Sets the width value for the object.
Parameters
value The value of which to set width to.
Definition at line 88 of file Texture.hpp.
SetWrap()
Texture & raylib::Texture::SetWrap (int wrapMode) inline
Set texture wrapping mode.
Definition at line 204 of file Texture.hpp.
Unload()
void raylib::Texture::Unload () inline
Unload texture from GPU memory (VRAM)
Definition at line 151 of file Texture.hpp.
Referenced by ~Texture(), and operator=().
Update() [1/2]
Texture & raylib::Texture::Update (::Rectangle rec, const void * pixels) inline
Update GPU texture rectangle with new data.
Definition at line 166 of file Texture.hpp.
Update() [2/2]
Texture & raylib::Texture::Update (const void * pixels) inline
Update GPU texture with new data.
Definition at line 158 of file Texture.hpp.