raylib-cpp: raylib::RayHitInfo Class Reference
raylib::RayHitInfo Class Reference
Public Member Functions
RayHitInfo (::RayHitInfo ray)
RayHitInfo (bool Hit, float Distance, ::Vector3 Position, ::Vector3 Normal)
float GetDistance ()
bool GetHit ()
inline ::Vector3 GetNormal ()
inline ::Vector3 GetPosition ()
RayHitInfo & operator= (const ::RayHitInfo &ray)
RayHitInfo & operator= (const RayHitInfo &ray)
void set (::RayHitInfo ray)
void SetDistance (float value)
void SetHit (bool value)
void SetNormal (::Vector3 value)
void SetPosition (::Vector3 value)
Detailed Description
Definition at line 15 of file RayHitInfo.hpp.
Constructor & Destructor Documentation
RayHitInfo() [1/2]
raylib::RayHitInfo::RayHitInfo (::RayHitInfo ray) inline
Definition at line 17 of file RayHitInfo.hpp.
References set().
RayHitInfo() [2/2]
raylib::RayHitInfo::RayHitInfo (bool Hit, float Distance, ::Vector3 Position, ::Vector3 Normal) inline
Definition at line 21 of file RayHitInfo.hpp.
Member Function Documentation
GetDistance()
float raylib::RayHitInfo::GetDistance () inline
Definition at line 46 of file RayHitInfo.hpp.
GetHit()
bool raylib::RayHitInfo::GetHit () inline
Definition at line 45 of file RayHitInfo.hpp.
GetNormal()
inline ::Vector3 raylib::RayHitInfo::GetNormal () inline
Definition at line 48 of file RayHitInfo.hpp.
GetPosition()
inline ::Vector3 raylib::RayHitInfo::GetPosition () inline
Definition at line 47 of file RayHitInfo.hpp.
operator=() [1/2]
RayHitInfo& raylib::RayHitInfo::operator= (const ::RayHitInfo & ray) inline
Definition at line 28 of file RayHitInfo.hpp.
References set().
operator=() [2/2]
RayHitInfo& raylib::RayHitInfo::operator= (const RayHitInfo & ray) inline
Definition at line 33 of file RayHitInfo.hpp.
References set().
set()
void raylib::RayHitInfo::set (::RayHitInfo ray) inline
Definition at line 38 of file RayHitInfo.hpp.
Referenced by operator=(), and RayHitInfo().
SetDistance()
void raylib::RayHitInfo::SetDistance (float value) inline
Definition at line 46 of file RayHitInfo.hpp.
SetHit()
void raylib::RayHitInfo::SetHit (bool value) inline
Definition at line 45 of file RayHitInfo.hpp.
SetNormal()
void raylib::RayHitInfo::SetNormal (::Vector3 value) inline
Definition at line 48 of file RayHitInfo.hpp.
SetPosition()
void raylib::RayHitInfo::SetPosition (::Vector3 value) inline
Definition at line 47 of file RayHitInfo.hpp.