raylib-cpp: raylib::Physics Class Reference
raylib::Physics Class Reference
Public Member Functions
Physics ()
Physics (float gravityX, float gravityY)
~Physics ()
Physics & AddForce (PhysicsBody body, Vector2 force)
Physics & AddTorque (PhysicsBody body, float amount)
Physics & Close ()
PhysicsBody CreateBodyCircle (Vector2 pos, float radius, float density)
PhysicsBody CreateBodyPolygon (Vector2 pos, float radius, int sides, float density)
PhysicsBody CreateBodyRectangle (Vector2 pos, float width, float height, float density)
Physics & DestroyBody (PhysicsBody body)
int GetBodiesCount ()
PhysicsBody GetBody (int index)
int GetShapeType (int index)
Vector2 GetShapeVertex (PhysicsBody body, int vertex)
int GetShapeVerticesCount (int index)
Physics & Init ()
bool IsEnabled ()
Physics & Reset ()
Physics & RunStep ()
Physics & SetBodyRotation (PhysicsBody body, float radians)
Physics & SetGravity (float x, float y)
Physics & SetTimeStep (double delta)
Physics & Shatter (PhysicsBody body, Vector2 position, float force)
Detailed Description
Definition at line 16 of file Physics.hpp.
Constructor & Destructor Documentation
Physics() [1/2]
raylib::Physics::Physics () inline
Definition at line 18 of file Physics.hpp.
References Init().
                   {
             Init();
         };
Physics() [2/2]
raylib::Physics::Physics (float gravityX, float gravityY) inline
Definition at line 21 of file Physics.hpp.
References Init(), and SetGravity().
{
             Init();
             SetGravity(gravityX, gravityY);
         };
~Physics()
raylib::Physics::~Physics () inline
Definition at line 26 of file Physics.hpp.
References Close().
                    {
             Close();
         }
Member Function Documentation
AddForce()
Physics& raylib::Physics::AddForce (PhysicsBody body, Vector2 force) inline
Definition at line 68 of file Physics.hpp.
{
             ::PhysicsAddForce(body, force);
             return *this;
         }
AddTorque()
Physics& raylib::Physics::AddTorque (PhysicsBody body, float amount) inline
Definition at line 72 of file Physics.hpp.
{
             ::PhysicsAddTorque(body, amount);
             return *this;
         }
Close()
Physics& raylib::Physics::Close () inline
Definition at line 35 of file Physics.hpp.
Referenced by ~Physics().
{
             ::ClosePhysics();
             return *this;
         }
CreateBodyCircle()
PhysicsBody raylib::Physics::CreateBodyCircle (Vector2 pos, float radius, float density) inline
Definition at line 59 of file Physics.hpp.
{
             return ::CreatePhysicsBodyCircle(pos, radius, density);
         }
CreateBodyPolygon()
PhysicsBody raylib::Physics::CreateBodyPolygon (Vector2 pos, float radius, int sides, float density) inline
Definition at line 65 of file Physics.hpp.
{
             return ::CreatePhysicsBodyPolygon(pos, radius, sides, density);
         }
CreateBodyRectangle()
PhysicsBody raylib::Physics::CreateBodyRectangle (Vector2 pos, float width, float height, float density) inline
Definition at line 62 of file Physics.hpp.
{
             return ::CreatePhysicsBodyRectangle(pos, width, height, density);
         }
DestroyBody()
Physics& raylib::Physics::DestroyBody (PhysicsBody body) inline
Definition at line 99 of file Physics.hpp.
{
             ::DestroyPhysicsBody(body);
             return *this;
         }
GetBodiesCount()
int raylib::Physics::GetBodiesCount () inline
Definition at line 80 of file Physics.hpp.
{
             return ::GetPhysicsBodiesCount();
         }
GetBody()
PhysicsBody raylib::Physics::GetBody (int index) inline
Definition at line 83 of file Physics.hpp.
{
             return ::GetPhysicsBody(index);
         }
GetShapeType()
int raylib::Physics::GetShapeType (int index) inline
Definition at line 86 of file Physics.hpp.
{
             return ::GetPhysicsShapeType(index);
         }
GetShapeVertex()
Vector2 raylib::Physics::GetShapeVertex (PhysicsBody body, int vertex) inline
Definition at line 92 of file Physics.hpp.
{
             return ::GetPhysicsShapeVertex(body, vertex);
         }
GetShapeVerticesCount()
int raylib::Physics::GetShapeVerticesCount (int index) inline
Definition at line 89 of file Physics.hpp.
{
             return ::GetPhysicsShapeVerticesCount(index);
         }
Init()
Physics& raylib::Physics::Init () inline
Definition at line 30 of file Physics.hpp.
Referenced by Physics().
{
             ::InitPhysics();
             return *this;
         }
IsEnabled()
bool raylib::Physics::IsEnabled () inline
Definition at line 50 of file Physics.hpp.
{
             return ::IsPhysicsEnabled();
         }
Reset()
Physics& raylib::Physics::Reset () inline
Definition at line 103 of file Physics.hpp.
{
             ::ResetPhysics();
             return *this;
         }
RunStep()
Physics& raylib::Physics::RunStep () inline
Definition at line 40 of file Physics.hpp.
{
             ::RunPhysicsStep();
             return *this;
         }
SetBodyRotation()
Physics& raylib::Physics::SetBodyRotation (PhysicsBody body, float radians) inline
Definition at line 95 of file Physics.hpp.
{
             ::SetPhysicsBodyRotation(body, radians);
             return *this;
         }
SetGravity()
Physics& raylib::Physics::SetGravity (float x, float y) inline
Definition at line 54 of file Physics.hpp.
Referenced by Physics().
{
             ::SetPhysicsGravity(x, y);
             return *this;
         }
SetTimeStep()
Physics& raylib::Physics::SetTimeStep (double delta) inline
Definition at line 45 of file Physics.hpp.
{
             ::SetPhysicsTimeStep(delta);
             return *this;
         }
Shatter()
Physics& raylib::Physics::Shatter (PhysicsBody body, Vector2 position, float force) inline
Definition at line 76 of file Physics.hpp.
{
             ::PhysicsShatter(body, position, force);
             return *this;
         }