raylib-cpp: raylib::VrStereoConfig Class Reference
raylib::VrStereoConfig Class Reference
VR stereo config functions for VR simulator.
#include <VrStereoConfig.hpp>
Public Member Functions
VrStereoConfig (const ::VrDeviceInfo &info)
~VrStereoConfig ()
Unload VR stereo config.
VrStereoConfig & BeginMode ()
Begin stereo rendering.
VrStereoConfig & EndDrawing ()
End stereo rendering.
void Init (const ::VrDeviceInfo &info)
Load VR stereo config for VR simulator device parameters.
void Unload ()
Unload VR stereo config.
Detailed Description
VR stereo config functions for VR simulator.
Definition at line 11 of file VrStereoConfig.hpp.
Constructor & Destructor Documentation
VrStereoConfig()
raylib::VrStereoConfig::VrStereoConfig (const ::VrDeviceInfo & info) inline
Definition at line 13 of file VrStereoConfig.hpp.
References Init().
~VrStereoConfig()
raylib::VrStereoConfig::~VrStereoConfig () inline
Unload VR stereo config.
Definition at line 27 of file VrStereoConfig.hpp.
References Unload().
Member Function Documentation
BeginMode()
VrStereoConfig & raylib::VrStereoConfig::BeginMode () inline
Begin stereo rendering.
Definition at line 34 of file VrStereoConfig.hpp.
EndDrawing()
VrStereoConfig & raylib::VrStereoConfig::EndDrawing () inline
End stereo rendering.
Definition at line 42 of file VrStereoConfig.hpp.
Init()
void raylib::VrStereoConfig::Init (const ::VrDeviceInfo & info) inline
Load VR stereo config for VR simulator device parameters.
Definition at line 20 of file VrStereoConfig.hpp.
Referenced by VrStereoConfig().
Unload()
void raylib::VrStereoConfig::Unload () inline
Unload VR stereo config.
Definition at line 50 of file VrStereoConfig.hpp.
Referenced by ~VrStereoConfig().