raylib-cpp: raylib::Vector2 Class Reference
raylib::Vector2 Class Reference
Vector2 type.
#include <Vector2.hpp>
Public Member Functions
Vector2 ()
Vector2 (const ::Vector2 &vec)
Vector2 (float x)
Vector2 (float x, float y)
Vector2 Add (const ::Vector2 &vector2) const
float Angle (const ::Vector2 &vector2) const
Calculate angle from two vectors in X-axis.
bool CheckCollision (::Rectangle rec) const
Check if point is inside rectangle.
bool CheckCollision (::Vector2 center, float radius) const
Check if point is inside circle.
bool CheckCollision (::Vector2 p1, ::Vector2 p2, ::Vector2 p3) const
Check if point is inside a triangle.
bool CheckCollisionCircle (float radius, ::Rectangle rec) const
Check collision between circle and rectangle.
bool CheckCollisionCircle (float radius1, ::Vector2 center2, float radius2) const
Check collision between two circles.
bool CheckCollisionLines (::Vector2 endPos1, ::Vector2 startPos2, ::Vector2 endPos2, ::Vector2 *collisionPoint) const
Check the collision between two lines defined by two points each, returns collision point by reference.
float Distance (const ::Vector2 &vector2) const
Calculate distance between two vectors.
Vector2 Divide (const ::Vector2 &vector2) const
Vector2 Divide (const float div) const
float DotProduct (const ::Vector2 &vector2) const
Calculate two vectors dot product.
Vector2 & DrawCircle (float radius, ::Color color)
Draw a color-filled circle (Vector version)
Vector2 & DrawLine (::Vector2 endPos, ::Color color)
Vector2 & DrawLine (::Vector2 endPos, float thick, ::Color color)
Vector2 & DrawLineBezier (::Vector2 endPos, float thick, ::Color color)
Vector2 & DrawLineBezierQuad (::Vector2 endPos, ::Vector2 controlPos, float thick, ::Color color)
Draw line using quadratic bezier curves with a control point.
Vector2 & DrawPixel (::Color color)
Vector2 & DrawPoly (int sides, float radius, float rotation, ::Color color)
Vector2 & DrawRectangle (::Vector2 size, ::Color color)
float GetX () const
Retrieves the x value for the object.
float GetY () const
Retrieves the y value for the object.
float Length () const
Calculate vector length.
float LengthSqr () const
Calculate vector square length.
Vector2 Lerp (const ::Vector2 &vector2, float amount) const
Calculate linear interpolation between two vectors.
Vector2 MoveTowards (const ::Vector2 &target, float maxDistance) const
Move Vector towards target.
Vector2 Multiply (const ::Vector2 &vector2) const
Vector2 Negate () const
Vector2 Normalize () const
Normalize provided vector.
bool operator!= (const ::Vector2 &other)
Vector2 operator* (const ::Vector2 &vector2) const
Vector2 operator* (const float scale) const
Vector2 & operator*= (const ::Vector2 &vector2)
Vector2 & operator*= (const float scale)
Vector2 operator+ (const ::Vector2 &vector2) const
Vector2 & operator+= (const ::Vector2 &vector2)
Vector2 operator- () const
Vector2 operator- (const ::Vector2 &vector2) const
Vector2 & operator-= (const ::Vector2 &vector2)
Vector2 operator/ (const ::Vector2 &vector2) const
Vector2 operator/ (const float div) const
Vector2 & operator/= (const ::Vector2 &vector2)
Vector2 & operator/= (const float div)
Vector2 & operator= (const ::Vector2 &vector2)
bool operator== (const ::Vector2 &other)
Vector2 Reflect (const ::Vector2 &normal) const
Calculate reflected vector to normal.
Vector2 Rotate (float degrees) const
Rotate Vector by float in Degrees.
Vector2 Scale (const float scale) const
void SetX (float value)
Sets the x value for the object.
void SetY (float value)
Sets the y value for the object.
Vector2 Subtract (const ::Vector2 &vector2) const
Static Public Member Functions
static Vector2 One ()
Vector with components value 1.0f.
static Vector2 Zero ()
Vector with components value 0.0f.
Detailed Description
Vector2 type.
Definition at line 16 of file Vector2.hpp.
Constructor & Destructor Documentation
Vector2() [1/4]
raylib::Vector2::Vector2 (const ::Vector2 & vec) inline
Definition at line 18 of file Vector2.hpp.
Vector2() [2/4]
raylib::Vector2::Vector2 (float x, float y) inline
Definition at line 22 of file Vector2.hpp.
Vector2() [3/4]
raylib::Vector2::Vector2 (float x) inline
Definition at line 23 of file Vector2.hpp.
Vector2() [4/4]
raylib::Vector2::Vector2 () inline
Definition at line 24 of file Vector2.hpp.
Member Function Documentation
Add()
Vector2 raylib::Vector2::Add (const ::Vector2 & vector2) const inline
Definition at line 44 of file Vector2.hpp.
Angle()
float raylib::Vector2::Angle (const ::Vector2 & vector2) const inline
Calculate angle from two vectors in X-axis.
Definition at line 169 of file Vector2.hpp.
CheckCollision() [1/3]
bool raylib::Vector2::CheckCollision (::Rectangle rec) const inline
Check if point is inside rectangle.
Definition at line 290 of file Vector2.hpp.
CheckCollision() [2/3]
bool raylib::Vector2::CheckCollision (::Vector2 center, float radius) const inline
Check if point is inside circle.
Definition at line 297 of file Vector2.hpp.
CheckCollision() [3/3]
bool raylib::Vector2::CheckCollision (::Vector2 p1, ::Vector2 p2, ::Vector2 p3) const inline
Check if point is inside a triangle.
Definition at line 304 of file Vector2.hpp.
CheckCollisionCircle() [1/2]
bool raylib::Vector2::CheckCollisionCircle (float radius, ::Rectangle rec) const inline
Check collision between circle and rectangle.
Definition at line 283 of file Vector2.hpp.
CheckCollisionCircle() [2/2]
bool raylib::Vector2::CheckCollisionCircle (float radius1, ::Vector2 center2, float radius2) const inline
Check collision between two circles.
Definition at line 276 of file Vector2.hpp.
CheckCollisionLines()
bool raylib::Vector2::CheckCollisionLines (::Vector2 endPos1, ::Vector2 startPos2, ::Vector2 endPos2, ::Vector2 * collisionPoint) const inline
Check the collision between two lines defined by two points each, returns collision point by reference.
Definition at line 311 of file Vector2.hpp.
Distance()
float raylib::Vector2::Distance (const ::Vector2 & vector2) const inline
Calculate distance between two vectors.
Definition at line 176 of file Vector2.hpp.
Divide() [1/2]
Vector2 raylib::Vector2::Divide (const ::Vector2 & vector2) const inline
Definition at line 84 of file Vector2.hpp.
Referenced by operator/().
Divide() [2/2]
Vector2 raylib::Vector2::Divide (const float div) const inline
Definition at line 92 of file Vector2.hpp.
DotProduct()
float raylib::Vector2::DotProduct (const ::Vector2 & vector2) const inline
Calculate two vectors dot product.
Definition at line 162 of file Vector2.hpp.
DrawCircle()
Vector2 & raylib::Vector2::DrawCircle (float radius, ::Color color) inline
Draw a color-filled circle (Vector version)
Definition at line 258 of file Vector2.hpp.
DrawLine() [1/2]
Vector2 & raylib::Vector2::DrawLine (::Vector2 endPos, ::Color color) inline
Definition at line 228 of file Vector2.hpp.
DrawLine() [2/2]
Vector2 & raylib::Vector2::DrawLine (::Vector2 endPos, float thick, ::Color color) inline
Definition at line 233 of file Vector2.hpp.
DrawLineBezier()
Vector2 & raylib::Vector2::DrawLineBezier (::Vector2 endPos, float thick, ::Color color) inline
Definition at line 238 of file Vector2.hpp.
References DrawLineBezier().
Referenced by DrawLineBezier().
DrawLineBezierQuad()
Vector2 & raylib::Vector2::DrawLineBezierQuad (::Vector2 endPos, ::Vector2 controlPos, float thick, ::Color color) inline
Draw line using quadratic bezier curves with a control point.
Definition at line 246 of file Vector2.hpp.
References DrawLineBezierQuad().
Referenced by DrawLineBezierQuad().
DrawPixel()
Vector2 & raylib::Vector2::DrawPixel (::Color color) inline
Definition at line 223 of file Vector2.hpp.
DrawPoly()
Vector2 & raylib::Vector2::DrawPoly (int sides, float radius, float rotation, ::Color color) inline
Definition at line 268 of file Vector2.hpp.
References DrawPoly().
Referenced by DrawPoly().
DrawRectangle()
Vector2 & raylib::Vector2::DrawRectangle (::Vector2 size, ::Color color) inline
Definition at line 263 of file Vector2.hpp.
GetX()
float raylib::Vector2::GetX () const inline
Retrieves the x value for the object.
Returns
The x value of the object.
Definition at line 26 of file Vector2.hpp.
GetY()
float raylib::Vector2::GetY () const inline
Retrieves the y value for the object.
Returns
The y value of the object.
Definition at line 27 of file Vector2.hpp.
Length()
float raylib::Vector2::Length () const inline
Calculate vector length.
Definition at line 141 of file Vector2.hpp.
LengthSqr()
float raylib::Vector2::LengthSqr () const inline
Calculate vector square length.
Definition at line 148 of file Vector2.hpp.
Lerp()
Vector2 raylib::Vector2::Lerp (const ::Vector2 & vector2, float amount) const inline
Calculate linear interpolation between two vectors.
Definition at line 183 of file Vector2.hpp.
MoveTowards()
Vector2 raylib::Vector2::MoveTowards (const ::Vector2 & target, float maxDistance) const inline
Move Vector towards target.
Definition at line 204 of file Vector2.hpp.
Multiply()
Vector2 raylib::Vector2::Multiply (const ::Vector2 & vector2) const inline
Definition at line 68 of file Vector2.hpp.
Negate()
Vector2 raylib::Vector2::Negate () const inline
Definition at line 60 of file Vector2.hpp.
Normalize()
Vector2 raylib::Vector2::Normalize () const inline
Normalize provided vector.
Definition at line 155 of file Vector2.hpp.
One()
static Vector2 raylib::Vector2::One () inline static
Vector with components value 1.0f.
Definition at line 218 of file Vector2.hpp.
operator!=()
bool raylib::Vector2::operator!= (const ::Vector2 & other) inline
Definition at line 39 of file Vector2.hpp.
operator*() [1/2]
Vector2 raylib::Vector2::operator* (const ::Vector2 & vector2) const inline
Definition at line 72 of file Vector2.hpp.
operator*() [2/2]
Vector2 raylib::Vector2::operator* (const float scale) const inline
Definition at line 80 of file Vector2.hpp.
operator*=() [1/2]
Vector2 & raylib::Vector2::operator*= (const ::Vector2 & vector2) inline
Definition at line 113 of file Vector2.hpp.
operator*=() [2/2]
Vector2 & raylib::Vector2::operator*= (const float scale) inline
Definition at line 119 of file Vector2.hpp.
operator+()
Vector2 raylib::Vector2::operator+ (const ::Vector2 & vector2) const inline
Definition at line 48 of file Vector2.hpp.
operator+=()
Vector2 & raylib::Vector2::operator+= (const ::Vector2 & vector2) inline
Definition at line 100 of file Vector2.hpp.
operator-() [1/2]
Vector2 raylib::Vector2::operator- () const inline
Definition at line 64 of file Vector2.hpp.
operator-() [2/2]
Vector2 raylib::Vector2::operator- (const ::Vector2 & vector2) const inline
Definition at line 56 of file Vector2.hpp.
operator-=()
Vector2 & raylib::Vector2::operator-= (const ::Vector2 & vector2) inline
Definition at line 106 of file Vector2.hpp.
operator/() [1/2]
Vector2 raylib::Vector2::operator/ (const ::Vector2 & vector2) const inline
Definition at line 88 of file Vector2.hpp.
operator/() [2/2]
Vector2 raylib::Vector2::operator/ (const float div) const inline
Definition at line 96 of file Vector2.hpp.
References Divide().
operator/=() [1/2]
Vector2 & raylib::Vector2::operator/= (const ::Vector2 & vector2) inline
Definition at line 125 of file Vector2.hpp.
operator/=() [2/2]
Vector2 & raylib::Vector2::operator/= (const float div) inline
Definition at line 131 of file Vector2.hpp.
operator=()
Vector2 & raylib::Vector2::operator= (const ::Vector2 & vector2) inline
Definition at line 29 of file Vector2.hpp.
operator==()
bool raylib::Vector2::operator== (const ::Vector2 & other) inline
Definition at line 34 of file Vector2.hpp.
Reflect()
Vector2 raylib::Vector2::Reflect (const ::Vector2 & normal) const inline
Calculate reflected vector to normal.
Definition at line 190 of file Vector2.hpp.
Rotate()
Vector2 raylib::Vector2::Rotate (float degrees) const inline
Rotate Vector by float in Degrees.
Definition at line 197 of file Vector2.hpp.
Scale()
Vector2 raylib::Vector2::Scale (const float scale) const inline
Definition at line 76 of file Vector2.hpp.
SetX()
void raylib::Vector2::SetX (float value) inline
Sets the x value for the object.
Parameters
value The value of which to set x to.
Definition at line 26 of file Vector2.hpp.
SetY()
void raylib::Vector2::SetY (float value) inline
Sets the y value for the object.
Parameters
value The value of which to set y to.
Definition at line 27 of file Vector2.hpp.
Subtract()
Vector2 raylib::Vector2::Subtract (const ::Vector2 & vector2) const inline
Definition at line 52 of file Vector2.hpp.
Zero()
static Vector2 raylib::Vector2::Zero () inline static
Vector with components value 0.0f.
Definition at line 211 of file Vector2.hpp.